### ISSUE TITLE
Please add all requested enhancements to here

### ISSUE THREAD

**Issue by zbot473** [zbot473/SurvivHacks#1]
If you want anything added say it here. 
If you want something fixed, make a new issue

**Comment by ALEXXANDRO23** [comment]
Hello friend, the hack has been patched, you could update it pls :C

**Comment by zbot473** [comment]
will do.

**Comment by zbot473** [comment]
@ALEXXANDRO23 Try the 0.6.0-patch branch 
<img width="1298" alt="screen shot 2018-09-08 at 1 48 31 pm" src="https://user-images.githubusercontent.com/13140490/45257076-239bfd00-b36e-11e8-8053-e5b3c2817b64.png">

**Comment by ALEXXANDRO23** [comment]
friend does not work I downloaded the 0.6.0 and nothing

**Comment by ALEXXANDRO23** [comment]
:(

**Comment by zbot473** [comment]
What does it say?

**Comment by IME9** [comment]
@zbot473  https://gyazo.com/a59d0ccda4acbe0acfe9b7e948ddc62e

**Comment by zbot473** [comment]
Im trying to fix that

**Comment by IME9** [comment]
@zbot473  Oki sorry for the bunch of mentions lol I kinda freaked out because this seems like the end of cheating in surviv.io :disappointed:

**Comment by ALEXXANDRO23** [comment]
we depend on you @zbot473 :,c

**Comment by asianhacks** [comment]
Could u make the streamer mode thing?
