### ISSUE TITLE
Fix the switch gun

### ISSUE THREAD

**Issue by FallingBoi** [zbot473/SurvivHacks#101]
PLs fix it.

**Comment by Drew12473** [comment]
when you push right click it doesn't do anything.

**Comment by zbot473** [comment]
ok ill revert it. I made it so you use right click to auto aim

**Comment by RuanTM** [comment]
zbot 
put to activate the aimbot and disable the aimbot instead of sh

**Comment by zbot473** [comment]
?????

**Comment by RuanTM** [comment]
understood?

**Comment by RuanTM** [comment]
???????

**Comment by ALEXXANDRO23** [comment]
@zbot473   there will be the possibility that there is an option to put the correct button, to change the weapon .......... it is easier with the right button  :(

**Comment by IME9** [comment]
No don't revoke the change.

Just hit "1 or 2" for your weapons you lazy people.

Having a manual target is way more clean and easier to use.

You don't have to kill the first person in your sight and you can loot in peace.

**Comment by ALEXXANDRO23** [comment]
@IME9 the problem is not whether you are lazy or not but the comfort of changing weapons faster ...... Ati it is difficult for you to plunder? .... I doubt that someone else is difficult is more I think we are many who you want the weapon change with right click

**Comment by alexvornoffice** [comment]
right click for guns switching +1, for aim -> space key :)

**Comment by BachaBajceps** [comment]
I think that the best option will be binding a own key.

**Comment by zbot473** [comment]
I guess it's fixed
