### ISSUE TITLE
Menu of keys

### ISSUE THREAD

**Issue by FallingBoi** [zbot473/SurvivHacks#102]
Maybe can be a Menu where u can change the keys for: Swithc guns, Toggle Auto Aim, Zoom Enabled, etc.
U know for be most ez to control it 
PS: PLz dont change the Switch Gun Right Click to Toggle Aim Right Click :(

**Comment by ALEXXANDRO23** [comment]
@FallingBoi totally in agreement........ hopefully and return the change of weapon with right click

**Comment by FallingBoi** [comment]
@ALEXXANDRO23 Yeah :(

**Comment by RuanTM** [comment]
hehe -> https://prnt.sc/lmq4ks

**Comment by zbot473** [comment]
I didnt know a lot of you used that.  I'll make a toggle for it. A keybind menu would take too long to create

**Comment by FallingBoi** [comment]
@zbot473 Ok zbot, np is only a suggestion. And i use so much the Weapon Change.

**Comment by zbot473** [comment]
Oh
