### ISSUE TITLE
Multibox bot movement problem

### ISSUE THREAD

**Issue by alexvornoffice** [zbot473/SurvivHacks#103]
Maybe make bot follow the path of the first main player and not to copy the movement...
The bot is replicating key-presses and the result is awful. It get's lost somewhere...

**Comment by zbot473** [comment]
How would you suggest to copy the path

**Comment by alexvornoffice** [comment]
take positions of the main player and store them in an array;
make the bot move to the points of the array on the map. Like this? :D

**Comment by zbot473** [comment]
The array would need to be huge

**Comment by alexvornoffice** [comment]
store new values in the array once per second or half the second.
