### ISSUE TITLE
Switch Guns

### ISSUE THREAD

**Issue by FallingBoi** [zbot473/SurvivHacks#104]
Will change weapons quickly be with the right button of mouse or it will be used for toggle the aimbot?
I'm very confused and idk what will do zbot :(
I want to change the weapons its very useful 4 m3.

**Comment by ALEXXANDRO23** [comment]
@alexvornoffice Really, you can have the weapon change back with a right click  ;DDD

**Comment by ALEXXANDRO23** [comment]
It would be great if you could now everything is very confusing without the right click to change the weapon :/

**Comment by RuanTM** [comment]
yes, it would help too much to change weapons in the right back button

**Comment by zbot473** [comment]
I think i changed it. Try reinstalling the hack

**Comment by ALEXXANDRO23** [comment]
@zbot473 it does not work you can not change the weapon with the right button :,c

**Comment by zbot473** [comment]
hmm

**Comment by zbot473** [comment]
@ALEXXANDRO23 try reinstalling now

**Comment by ALEXXANDRO23** [comment]
now the autoaim is activated with the right click automatically and I do not like that option (I prefer just pressing the Z key for the auto aim) .... I deactivate the option of * right click alternate * and * change the pistol * and they are activated again :

**Comment by ALEXXANDRO23** [comment]
everything is very confusing now I thought that the option (rightclicktoggle) was to change the weapon with the right button but it is not like this: C

**Comment by zbot473** [comment]
does it work?

**Comment by ALEXXANDRO23** [comment]
@zbot473 It does not work everything remains the same.
