### ISSUE TITLE
Hack Not Working

### ISSUE THREAD

**Issue by RuanTM** [zbot473/SurvivHacks#106]
Hacking Not Working...

**Comment by colkat406** [comment]
same for me not working

**Comment by alexvornoffice** [comment]
play without hack or fix https://github.com/zbot473/SurvivHacks/blob/master/CONTRIBUTING.md

**Comment by ALEXXANDRO23** [comment]
I would help with pleasure but English is not my language

**Comment by YESS808** [comment]
alexvornoffice: Does the Python script still work to automagically update the exports?

**Comment by alexvornoffice** [comment]
> alexvornoffice: Does the Python script still work to automagically update the exports?

I don't know
