### ISSUE TITLE
congratulations

### ISSUE THREAD

**Issue by ThanksMrSotarks** [zbot473/SurvivHacks#107]
you completely broke the cheat (at least with the exports)

**Comment by ALEXXANDRO23** [comment]
?

**Comment by alexvornoffice** [comment]
I fixed the hack works normal, aim is bad, maybe add dodge only against snipers and make bullets bigger somehow, and many more... you just fork the repo, make your own repo and add new features and propose you new features here.

**Comment by zbot473** [comment]
thx @alexvornoffice
