### ISSUE TITLE
Where's the right click to aim ?!!!!!!

### ISSUE THREAD

**Issue by IME9** [zbot473/SurvivHacks#109]
I want right click to aim wtf where is it its like the best thing ever please put it back its not in the settings aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by IME9** [comment]
OMG PUT IT BACK PLEASE BEING FORCED TO LOOK AT SOMEONE WHEN TRYING TO LOOT IS ANNOYING AF

ALSO WHENEVER A BULLET HITS YOU IT MAKE THE PAN SOUND LOL

**Comment by IME9** [comment]
PLEASE I VOUCH BUT THE RIGHT CLICK OPTION TO AIM SHOULD BE ADDED BACK PLEASE FOR ME IT WAS THE BEST WAY OF PLAYING THIS.

**Comment by IME9** [comment]
@zbot473  PLS SENPAI

**Comment by IME9** [comment]
"other people" are lazy they can just press 1 or 2

**Comment by alexvornoffice** [comment]
yeah, I am lazy :D

**Comment by IME9** [comment]
The speed from changing gun isn't **needed**

_While being able to loot without getting killed all the time is a need_

**Comment by alexvornoffice** [comment]
Look into code and uncomment the code, It is possible to make it how it was -> just look into source...

**Comment by IME9** [comment]
Well if it possible to just bind another key for manual aiming I'm for it.

I just really want to aim when I want with bot.

It would be better to add the option in the menu.

**But making it by default right click to switch gun is fine**

Just give an option to disable switch gun with right click and make RMB to aim

**Comment by IME9** [comment]
Couldn't you make a separate branch where switch gun isn't a thing and RMB is aiming ?

So people can choose to download the one they prefer

**Comment by IME9** [comment]
I think shift is fine for aiming but yes a patch is needed and I guess you or zbot won't do it before next needed update right ?

If I was good at scripting language  I would probably be messing around already.

**Comment by IME9** [comment]
```
    bind: function() {
                    var pos = getCurPos()
                    realMousePos.x = pos.x
                    realMousePos.y = pos.y
                    window.addEventListener("mousemove", getMousePos);

                    ! function n() {
                        switchWeapon(), o = setTimeout(n, 5e2)
                    }()

                    isBinded = true
                },

```

So uuh is this the bind variable to make switch work :thinking: 

Then I'd need the variable when RMB was aiming and the script part for making it a button gui thingy.

Oof this is too deep for my brain.

**Comment by IME9** [comment]
for now im just gonna deal with restriction angle but please make the next update have shift to aim manually. :heart:

**Comment by zbot473** [comment]
oh boi

**Comment by zbot473** [comment]
see this is what i mean there is a minority that actually needs this feature

**Comment by alexvornoffice** [comment]
people like me got used to this method of gun switching, pressing 2 or 1 is not good for me in this game, because I switch guns very often and I can not remember which gun key I have right now...
