### ISSUE TITLE
Shooting through a bushes and others

### ISSUE THREAD

**Issue by BachaBajceps** [zbot473/SurvivHacks#112]
J noticed that tigggerbot doesn't shoot through a **bushes**, Lily Pad, Leaf pile.
![bez tytulu](https://user-images.githubusercontent.com/23284748/49244605-7c7cae00-f410-11e8-8daf-e84f6b4bbfab.jpg)
I think that problem can be in this part of code: https://github.com/zbot473/SurvivHacks/blob/99ee520578275fc047672591ae6cb602337b918e/ChromeExtension/init.js#L3200-L3204
I have suggestion: **Shooting through a transparent** can be added like a red barrels.
![lol](https://user-images.githubusercontent.com/23284748/49245499-d2525580-f412-11e8-8a1d-5a9e1823c1fd.jpg)

**Comment by zbot473** [comment]
I'm pretty sure this exists

**Comment by BachaBajceps** [comment]
What exist?

**Comment by zbot473** [comment]
It shoots through bushes

**Comment by zbot473** [comment]
hmm

**Comment by zbot473** [comment]
I think i fixed it
