### ISSUE TITLE
0.6.1 update

### ISSUE THREAD

**Issue by ThanksMrSotarks** [zbot473/SurvivHacks#12]
can you find the gameclient source or nah

**Comment by zbot473** [comment]
Yeah that's pretty easy, im trying to fix the hack itself.

**Comment by ThanksMrSotarks** [comment]
thanks for update

**Comment by ThanksMrSotarks** [comment]
is the init file time-consuming or brain-consuming, cause i wanna help with these projects but i need to understand the basics

**Comment by zbot473** [comment]
The init file and background file.

**Comment by ThanksMrSotarks** [comment]
yes?

how do i fix those files by myself when a new update appears is what im meaning to ask ;-;

**Comment by zbot473** [comment]
Read my comment in  #16
