### ISSUE TITLE
the game just freezed after I use new update..

### ISSUE THREAD

**Issue by charlie45** [zbot473/SurvivHacks#122]
The game just freezed. not like quit or something, the game just got freezed

**Comment by RuanTM** [comment]
clearly, from one day to the other my game began to freeze ;-;

**Comment by Pokesterus** [comment]
same it wasnt freezing yesrerdat but now it is

**Comment by zbot473** [comment]
Check the console for when it says variable undefined or cannot find something of undefined (something will change)

**Comment by SirStoneyBologna** [comment]
I'm having the same issue as of today. I found out about this extension yesterday, fell in love with it and hope to see if it's still supported and will be fixed. I appreciate it regardless!

**Comment by ThanksMrSotarks** [comment]
@zbot473 ran the console while in game when it crashed, this is what it spitted out
![image](https://user-images.githubusercontent.com/43581418/49524267-101b0800-f871-11e8-8384-3404c808c2e0.png)
![image](https://user-images.githubusercontent.com/43581418/49524326-2b861300-f871-11e8-979e-deb7d611aac3.png)

**Comment by charlie45** [comment]
wow i didn't expect this amount of comments thanks for advise :)

**Comment by charlie45** [comment]
and thanksmrsotarks surviv2.io is freezing too :(

**Comment by charlie45** [comment]
@zbot473  is it the problem of their servers?

**Comment by ThanksMrSotarks** [comment]
did a testing, yeah it's the extension's problem, might take a while to fix

**Comment by ThanksMrSotarks** [comment]
@zbot473 the new source file seems changed **slightly** to mess with the auto deob program, but im checking it manually and see if it works.

**Comment by Pokesterus** [comment]
surviv2.io also doesent work

**Comment by charlie45** [comment]
@ThanksMrSotarks thanks for fixing it :)

**Comment by zbot473** [comment]
Did anyone save the code last week?

**Comment by killercloudj** [comment]
Yeah I did

**Comment by killercloudj** [comment]
[SurvivHacks-master (5).zip](https://github.com/zbot473/SurvivHacks/files/2650556/SurvivHacks-master.5.zip)

**Comment by killercloudj** [comment]
![screenshot 58](https://user-images.githubusercontent.com/38992642/49542757-681f3200-f8a4-11e8-8e3c-e717d4aaf295.png)

**Comment by Pokesterus** [comment]
still aint workin .-.

**Comment by killercloudj** [comment]
No

**Comment by killercloudj** [comment]
I am trying to help them by showing them the console

**Comment by charlie45** [comment]
> > @ThanksMrSotarks thanks for fixing it :)
> 
> its fixed for you?

no i mean he'll try it and i'm thank for it

**Comment by killercloudj** [comment]
What does this mean wallCount: 2, particle: "shackBreak", particleCount: 25, residue: "map-shack-res-02.img"}    ?

**Comment by alexvornoffice** [comment]
maybe it freezes because of bad servers, I can not replicate.

**Comment by IME9** [comment]
oh god whats going on

**Comment by IME9** [comment]
Hmm whenever I click for more info on the thing that  get looped it highlight this 


  console.log(game.scope)

![aaaaaaaaaaaaa](https://user-images.githubusercontent.com/19210871/49547868-ee8e4080-f8b1-11e8-8984-1d6f9dbc8b2b.PNG)

**Comment by IME9** [comment]
[surviv.io-1544048431510.log](https://github.com/zbot473/SurvivHacks/files/2650855/surviv.io-1544048431510.log)

idk if this can help

**Comment by ThanksMrSotarks** [comment]
@killercloudj you could show the part of the console with the red warning errors

**Comment by zbot473** [comment]
The diff shows nothing significant but ill have to check

**Comment by alexvornoffice** [comment]
I see in diff that they try to make it harder to update the cheat, variables are moved to different lines so when I try to check values I can not find the same text/keyword in the app.js file...

**Comment by charlie45** [comment]
hmm.. then they noticed the hack users? I thought they don't care about it..

**Comment by sobol3d** [comment]
they do notice it as some people start to put cheats on chrome store. as long as it was only here they do not care abut it

**Comment by ThanksMrSotarks** [comment]
Might have to reestablish the cheat guide and redefine the variables, cus they changed the position of everything, so deobing would be harder if we kept going like this .-.

**Comment by zbot473** [comment]
There isnt any deob. The game itself stops

**Comment by RuanTM** [comment]
> Não há nenhum deob. O jogo em si pára

omg

**Comment by alexvornoffice** [comment]
It will be **hard to fix**, I think, and who will pay for the effort? XD better **not to fix** :D 
People will spend less time on this game... Fixing will require to inspect a lot and maybe to fully recreate the plugin and to check what variable is not set correctly because this is what I think is the problem, debugging is hard and slow as the game can stop working after minutes of play so this will make a very slow inspection. I played thousand of matches - enough for me :P

**Comment by ThanksMrSotarks** [comment]
Well, it's been a good ride fellas. Surviv took half an year at least to fix a cheat xD

**Comment by IME9** [comment]
oh god rip

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/49612900-5c1b9900-f9a6-11e8-8d1d-1377ca1134f0.png)
In total, they did not add anything extraordinary...

**Comment by zbot473** [comment]
@PowerOfUniverse I dont have my computer right now so I would have fixed it

**Comment by RuanTM** [comment]
i love PowerOfUniverse

**Comment by IME9** [comment]
@PowerOfUniverse  OMG UPDATE PLS LOVE YOU DADDY

**Comment by charlie45** [comment]
@PowerOfUniverse  thanks man😆

**Comment by ThanksMrSotarks** [comment]
BLESS US PAPI UNIVERSE  @PowerOfUniverse

**Comment by Pokesterus** [comment]
nice

**Comment by sobol3d** [comment]
@PowerOfUniverse hey can you upload the code, or the file ?

**Comment by RuanTM** [comment]
aff, 
Ele nem vai fazer upload

**Comment by zbot473** [comment]
im not entierly sure but this may be the code we're looking for:
```Mt: function(e) {
                if (this.ws && this.ws.readyState == this.ws.OPEN) try {
                    this.ws.send(e.getBuffer())
                } catch (e) {
                    z.storeGeneric("error", "sendMessageException"), this.ws.close()
                }
            }
```

**Comment by zbot473** [comment]
try adding this to patch rules in background.js
```javascript
if\(this.ws\&\&.*?}.*?}
```

**Comment by Sam1370** [comment]
Hey guys, I found a workaround to this issue, not sure if it will work for you but it sure works for me. Basically what I do is each game I use a different gamemode: for example for game #1 I would push play solo, the next play duo, and then do solo again. I have no idea how this works but it works for me and I am getting no crashes. You do not have to play a full game in order to do this, you can go in a game and kill yourself immediately if you want. Hope this helps you out, if it doesn't work, try one of the alternative proxy sites doing this (I used http://2dbattleroyale.com). Use master branch.
