### ISSUE TITLE
Hotkey modules

### ISSUE THREAD

**Issue by Pokesterus** [zbot473/SurvivHacks#123]
Can we assign a hotkey to each module say i wanted to have auto aim but didnt want to go into the menu to change it i could press a certain button and it deactivates or activates

**Comment by RuanTM** [comment]
translating these 3 lines Pokesterus do you want keybind for such module?

**Comment by Pokesterus** [comment]
For the main ones such as dodging and healing and autoaim + trigger

**Comment by RuanTM** [comment]
keybind of autoaim = shift
