### ISSUE TITLE
Its crashes randomly

### ISSUE THREAD

**Issue by FallingBoi** [zbot473/SurvivHacks#125]

**Comment by IME9** [comment]
https://github.com/zbot473/SurvivHacks/issues/122 

Don't make shitpost @zbot473  is already aware and probably working on it. 
Also I noticed all hacks available had the same issues or related problem the same day I think something happened with the game itself

**Comment by alexvornoffice** [comment]
I have now the same problem, first game was OK, now the second and 3rd freezes... hmm...

**Comment by FallingBoi** [comment]
Yeah, @alexvornoffice

**Comment by FallingBoi** [comment]
@IME9 Sorry, idk it, im not very newed in this shet.

**Comment by zbot473** [comment]
@FallingBoi its fine. 
@IME9 be nice
