### ISSUE TITLE
Is the cheat over now ??

### ISSUE THREAD

**Issue by IME9** [zbot473/SurvivHacks#128]
What the hell happened.

Thank you for your time @zbot473  and @alexvornoffice into the continuation of @PowerOfUniverse  etc etc etc I can't keep up with this lol.

So did the devs did something to their games to prevent hacks ?

I just want to know.

**Comment by IME9** [comment]
Also new version is out is there a chance to just update the cheat or did the variables all changed ?

That would suck if they patched it ,_,

**Comment by zbot473** [comment]
dude be patient. I can't really work on fixing it now. when I get my computer back, ill try
