### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by IAmAHumanIThink** [zbot473/SurvivHacks#130]
Just need to update it, as it doesn't work with this version of the game.

**Comment by CarmeloCampos** [comment]
I'm not going either, it seems that they updated the game

![image](https://user-images.githubusercontent.com/31357533/49615456-9d4a8380-f97b-11e8-99f7-94dd583b31dc.png)

**Comment by IAmAHumanIThink** [comment]
yea

**Comment by Flyer-One** [comment]
Do you have an ETA of that update? I love this hack!
