### ISSUE TITLE
Honestly,you guys can just update the json and then worry about the changed position of scripts(it freezes after a certain amount of time so it won't immediately affect us). Just an suggestion.

### ISSUE THREAD

**Issue by WotDefek** [zbot473/SurvivHacks#132]
Just saying lol.

**Comment by zbot473** [comment]
Dude I don't have my computer

**Comment by RuanTM** [comment]
without comupator without hack?

**Comment by RuanTM** [comment]
speak to the power of the universe give uplod in the hack

**Comment by colkat406** [comment]
how do u update it yourself

**Comment by colkat406** [comment]
> Just saying lol.

how do u update it yourself

**Comment by WotDefek** [comment]
> > Just saying lol.
> 
> how do u update it yourself

It’s fairly simple,go to the JSON file and change the outdated version to the current one.

**Comment by WotDefek** [comment]
> Dude I don't have my computer

Do you mind to give an estimation till when you can get on your PC?

**Comment by zbot473** [comment]
It works for normal mode

**Comment by yarkoval** [comment]
> It works for normal mode

and then freezes after a while

**Comment by zbot473** [comment]
Oh

**Comment by CarmeloCampos** [comment]
The hack after updating is working, but it freezes after a short time (from 15 to 20 seconds when entering the game)

**Comment by CarmeloCampos** [comment]
By the way, the function of collecting weapons automatically is not this running ..? or is it my mistake?

**Comment by zbot473** [comment]
Ik.

**Comment by WotDefek** [comment]
![image](https://user-images.githubusercontent.com/45688646/49672993-f75e4e00-fa3a-11e8-8ae1-e30a98215daa.png)
Fixed the freezing issue

**Comment by IME9** [comment]
@WotDefek  Did you ? 

Is it adblock :joy:

**Comment by IME9** [comment]
@WotDefek  Dude what is it. 

You don't seems to be using this hack because I dont see the fps counter.

**Comment by IME9** [comment]
@WotDefek

**Comment by WotDefek** [comment]
> @WotDefek

It was background js, and I modify the script so it doesn't look obvious when playing and screenshotting.

**Comment by IME9** [comment]
@WotDefek  What do I do with background js then ?

**Comment by IME9** [comment]
@WotDefek  Can't you just give your edit to @zbot473  if its working.

I guess you don't want a lot of skids to use cheats.

**Comment by WotDefek** [comment]
> @WotDefek Can't you just give your edit to @zbot473 if its working.
> 
> I guess you don't want a lot of skids to use cheats.

In all honesty,what you said was correct.

**Comment by IME9** [comment]
@WotDefek Damn XD 

It make sense tho. 

Its harder to patch something that isn't known so if you're edit is like well done and your personal thing it will be harder for the devs to definitively block it since they dont have sights of it or where to find the source or even who made/use it.

It's sad, I'm not really that bad at the game I really use hacks for trolling. With ironic/iconic user name.

At one point I was calling myself "Very Obvious Hax" and had the aiming and smoothing to maximum level so it my guns were trigger moving all the time :joy: 

But yeah it does make sense it's just a bid sad.

**Comment by IME9** [comment]
@WotDefek Well if you don't mind just giving me a hint what to do I'll get on that and if I can fix it too I won't leak either. 

Well do as you please
