### ISSUE TITLE
Nice try, but now i cant do nothing.

### ISSUE THREAD

**Issue by FallingBoi** [zbot473/SurvivHacks#134]
U tried to fix the freeze but that doesnt works, now its freezes in the menu, u can press anything, put name etc.
But doesnt works anything, u can press but u cant enter in a game. :( 
![image](https://user-images.githubusercontent.com/44214112/49669520-35517700-fa27-11e8-99be-822a3524bd55.png)

**Comment by zbot473** [comment]
Reverted
