### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by R2nR2n** [zbot473/SurvivHacks#138]
First of all, I love the cheat. 

This may have already been reported, but they game keeps freezing a little bit in each round, hope you can take a look at this. Thanks!

**Comment by IME9** [comment]
Don't make shitpost, #122 @zbot473  is already aware.

**Comment by IME9** [comment]
You can go check my useless thread too I'm trying to gather informations as much as I can about the issue occuring. Maybe it will help.

**Comment by zbot473** [comment]
Known
