### ISSUE TITLE
Uh is it just me or if you try you know to play even if freezing may occur...

### ISSUE THREAD

**Issue by TheSatanicAngeI** [zbot473/SurvivHacks#139]
**What is the god damn key to put checkpoints and stuff ?!**

No seriously I can't get it lol

Without using the hack its like c + RMB or something but I tried everything I can't get the options to ask health or bullets etc cant put checkpoint or exclamation point on the map even if thats not a need maybe the function is corrupted ?

idk

**Comment by danzam284** [comment]
The best way I found to reduce freezing and crashing was:
- Right when the game starts click z to turn the hack off temporarily
- Hide in somewhere like a bush or a table
- Wait about 30 seconds
- Play normally with hack
So far it worked 5/6 times for me. The one time that it did not work, I crashed while I was hiding in the bush so I did not lose any progress.

**Comment by humphreygaming** [comment]
@IME9 the key for emotes is b and the key for team pings ( "checkpoints" ) is c+b
