### ISSUE TITLE
SUGGESTIONS!!!

### ISSUE THREAD

**Issue by TheSatanicAngeI** [zbot473/SurvivHacks#143]
### Here are my suggestions :laughing: 

**1.** Deobfuscate the code.

**2.** Re-make the entire hack using a different script language or built differently.

**3.** Make a anonymouse youtube channel where you showcase the  hack and put a shorten link for instance bit.ly where people can get to the github to download it and so make money to encourage your work.  (here : https://shorte.st/ & http://destyy.com/wCv1CO)

_If your problem is recording software there are plenty of easy pay software to crack. I use myself bandicam cracked._

**I will put a .zip with the current crack I'm using. BE AWARE it is possible that your antivirus think it is a virus or malware (because obviously it is) all you have to do is install Bandicam with the software in the folder and use the keygen.**

Proof of it being real lol : https://gyazo.com/ba285e877d4c24855873a83d098e99c8

**4.**  Do announcements in the Discord to request help for finding a solution and if the solution is found for instance freezing give a special role to the user who contributed the most.

**5.** Create a new branch where only the variables and auto aim options are available that means no auto loot or heal etc. To see if it isn't due to something broken.

**6.** For future implements/features make a poll using https://www.strawpoll.me/ and so the most voted one will be added in the discord.

**7.** Do other projets, personally I would follow your work if I like it and so will contribute if it affect me directly. You could make a lot of money out of hacks seriously. You don't need to consider making it pay-to-use since you can use ads on youtube and make a shorten link to this github where 10 visitors = 5$. 

_For the shorten case, please advise users in the desc of your videos that it is possible that re-direction not consented leads to scamful pages and or viruses and it is extremely recommended to have an anti-virus on._ 

**8.** Collab with other scripters/hackers, get into an arrangements where the profit is splitted idk or make bigger work together so it is faster releases and faster improvement.

> I always dreamed of becoming a scripter, mostly due to how my life goes but because I've always been fascinated with computers. I think it is the most extraordinary thing ever created by the human. I want to contribute into it! 

 

[Bandicam 4.0.1.1339 with crack.zip](https://github.com/zbot473/SurvivHacks/files/2660946/Bandicam.4.0.1.1339.with.crack.zip)

@zbot473

**Comment by TheSatanicAngeI** [comment]
Also the freezing might be due to an error in this 

`unbind: function() {
                        p(), window.removeEventListener("wheel", l), window.addEventListener("wheel", l), i ? Object.keys(i).map(function(n) {
yn = function() {
                        window.removeEventListener("keydown", fn), window.removeEventListener("keyup", bn), autoAim.isBinded() && autoAimUnbind(), autoLoot.isBinded() && au
   function Tn() {
                vn && (yn(), vn = false)
 hn = function(n) {
                        90 == n.which && (gn() || (vn ? (Tn(), G = true) : xn()))`

I can't tell why tho I'm no scripter so I have no idea what these do in the game in the first place but I feel like it is an error due to how console show it.

![ca8c49d8a9930b6cc1adcbff97a84a51](https://user-images.githubusercontent.com/19210871/49702315-e0e3fe00-fbc4-11e8-93e1-50220f6eefe4.png)

**Comment by TheSatanicAngeI** [comment]
**No sound named: sfx**
[VM2153.txt](https://github.com/zbot473/SurvivHacks/files/2660976/VM2153.txt)

![6c0d3edaf671732eea8f0862197ff599](https://user-images.githubusercontent.com/19210871/49702657-9795ad80-fbc8-11e8-9aa8-de59bc0b9197.png)

**Comment by FallingBoi** [comment]
Wth, ur a genius. i bet if u know code u can make big things.

**Comment by alexvornoffice** [comment]
power of universe has the hack working, ask him, maybe he will answer, he said some time ago he is selling his work with 70 euro so do you need the hack fully working go pay him 70 euros :D

**Comment by TheSatanicAngeI** [comment]
Id only buy it to leak it after :joy:  

I don't have money so its safe :shield:

**Comment by WotDefek** [comment]
LOL 50 euro? it took me about fucking 2 min to fix and he demands 50 euro hahahahaha

**Comment by alexvornoffice** [comment]
but all the code is deobfuscated...

**Comment by charlie45** [comment]
why did you changed your name? it was IME9..

**Comment by TheSatanicAngeI** [comment]
@charlie45  Because that sound like "Im 9" also its my old username back in the minecraft days.

Now its TheSatanicAngel but it was already taken so caps I

**Comment by zbot473** [comment]
@TheSatanicAngeI your code is the hack's code.

**Comment by charlie45** [comment]
@TheSatanicAngeI  KK :)

**Comment by TheSatanicAngeI** [comment]
@zbot473 What do you mean ? I did fork it right. 

It was just in case your account get banned or the thread get closed by admins or Something. 

We should make a back up of the latest version to avoid this.

Still I don't know what you mean by that.
