### ISSUE TITLE
EVERYONE VERY IMPORTANT INFORMATION ABOUT FREEZE ISSUE!!!

### ISSUE THREAD

**Issue by TheSatanicAngeI** [zbot473/SurvivHacks#144]
> Freeze problem seems to never occur if Transparency hack is disabled. ("Particles transparency level",
> 
> "Ceiling transparency level" and "Smoke alpha" are all set to 1)
> 
> So, cheating is detected as @LWJGLRobot  said?

_Originally posted by @surviv314 in https://github.com/zbot473/SurvivHacks/issues/141#issuecomment-445998737_

So the answer as been given!

**Comment by TheSatanicAngeI** [comment]
### I tested it myself if transparency is all set to 1 (smoke doesn't matter) I did 5 games fully and didn't froze!!!

**Comment by danzam284** [comment]
Thank you so much for sharing that discovery. This leaves 1 problem though. You do not see many crates or tanks so it is still hard to play. Still, thank you

**Comment by zbot473** [comment]
huh. intresting

**Comment by zbot473** [comment]
So this works 100%?

**Comment by zbot473** [comment]
I'll look for that now

**Comment by danzam284** [comment]
Satanic Angel deserves a round of applause

**Comment by zbot473** [comment]
^

**Comment by WotDefek** [comment]
yall are getting closer to fixing it

**Comment by zbot473** [comment]
@WotDefek was that a question?

**Comment by YungFK** [comment]
how do you disable transperency hack and the particles and smoke stuff. (Im new to this. Please dont roast me.)

**Comment by YungFK** [comment]
@zbot473 are you guys getting any closer to fixing this btw? I really love your work.

**Comment by charlie45** [comment]
I think I was wrong.. it isn't fixed....and I used this transparency something but it's still freezing...

**Comment by zbot473** [comment]
@YungFK open the menu and then click config or something then move the sliders in transparency to the right

**Comment by Reeyaad** [comment]
It's working, all thanks goes to @TheSatanicAngeI

**Comment by YungFK** [comment]
@zbot473 thanks

**Comment by lonemoon84** [comment]
The value doesn't need to be 1, I tried 0.9 and it seems ok.

**Comment by zbot473** [comment]
Maybe because the event is over

**Comment by danzam284** [comment]
Legit I get a win every single round I play now.

**Comment by ancientt** [comment]
it still sometimes freezes tho from my experience id say a 5% chance

**Comment by FallingBoi** [comment]
@TheSatanicAngeI U r   G  O  D  .

**Comment by oskar9991** [comment]
after update game is freezing even when transparency is all set to 1

**Comment by TheSatanicAngeI** [comment]
@oskar9991 Well you said the reason of the problem already ### UPDATE


Need to patch current version for the most recent one. 

Also need to add those crap

[0.6.8] - Dec. 13, 2018
- Added new obstacle: hardstone boulder.
- Added new skins: Desert Camo, Desert Ghillie.

**Comment by zbot473** [comment]
There is a new update. I'm closing this
