### ISSUE TITLE
Idea: Add enemies armor "level"

### ISSUE THREAD

**Issue by alexvornoffice** [zbot473/SurvivHacks#146]
Add above enemies heads armor level like 3 or 6, so it will be a text with info: Example: Level 1 or Level 6
Level 6 is maximum number: armor 3 + helmet 3...

**Comment by alexvornoffice** [comment]
![surviv-level](https://user-images.githubusercontent.com/1689187/49881511-7a5e1a80-fe26-11e8-92ca-1c99bcf9a614.png)

Concept demo

**Comment by colkat406** [comment]
it already sayes what level armour that they have

**Comment by alexvornoffice** [comment]
I say above the head not somewhere else u need fast info for fast decisions...

**Comment by colkat406** [comment]
well you can make a fast descison because it is in a place where it is visible
![image](https://user-images.githubusercontent.com/36088507/49895514-82c74d00-fe48-11e8-917e-9e77b76b53d0.png)

**Comment by colkat406** [comment]
well it is in a place where u can see it
![2](https://user-images.githubusercontent.com/36088507/49896202-8eb40e80-fe4a-11e8-9b92-19052566c85c.png)

**Comment by alexvornoffice** [comment]
I already did the patch maybe soon will upload...

**Comment by killercloudj** [comment]
Thanks for updating the hacks! 🥇

**Comment by zbot473** [comment]
@alexvornoffice please make a toggle

**Comment by zbot473** [comment]
or make a PR

**Comment by alexvornoffice** [comment]
no! I can not fix aim, help me somebody! :D
