### ISSUE TITLE
Fix the hack for new update pls

### ISSUE THREAD

**Issue by danzam284** [zbot473/SurvivHacks#147]
**Describe the bug**

**Screenshots**
Add photos of bugs from the console, if it is closely related to it.

**Desktop (please complete the following information):**
 - Browser version
 - Extension version [e.g. 1.0.70]

**Expected behavior**

**Additional context**

**Comment by zbot473** [comment]
Ok

**Comment by killercloudj** [comment]
Um the hack does not work.thank you for time you put in to this for us :)

**Comment by killercloudj** [comment]
![surviv io 2d battle royale game 1](https://user-images.githubusercontent.com/38992642/49974391-f465d080-ff06-11e8-8595-4cff17eafbf6.png)

**Comment by zbot473** [comment]
It works for me. Try updating.
