### ISSUE TITLE
Projects - Robot?

### ISSUE THREAD

**Issue by alexvornoffice** [zbot473/SurvivHacks#15]
What does it mean? So I imagine ultimate feature to make the cheat to work AUTOMATICALY?
I mean: make the hack 1. move 2. pick guns/ammo/armor 3. shot at everybody 4. win :D

**Comment by zbot473** [comment]
Yeah, I am working on autoswitch right now.

**Comment by zbot473** [comment]
Moving is the hardest part tho

**Comment by ThanksMrSotarks** [comment]
could just make something like an evolved autododge, and just add to let the bot run into the circle.

kinda like mobile sentry mode i'd say.

**Comment by alexvornoffice** [comment]
the bot needs to learn to destroy boxes and pick up weapons, but it can get stuck into building or other objects... so it need to detect what king of object is in his way and try to avoid them... I see this hard thing to do...

**Comment by zbot473** [comment]
The code is so complicated. I wish Powerofuniverse could give me the unobfuscated code
