### ISSUE TITLE
The extension can not work with this version of the game

### ISSUE THREAD

**Issue by miloslavche** [zbot473/SurvivHacks#151]
I'm sorry but I cannot load your cheat. 
![image](https://user-images.githubusercontent.com/41958056/49993411-60e4dc00-ffa8-11e8-8929-3675853270bf.png)

Browser – Chrome, 71.0.3578.98
Version of extension – 1.1.6.

May be cheat should be updated? 

Anyway, thanks!

**Comment by zbot473** [comment]
Fixed. Update
