### ISSUE TITLE
Auto Aim

### ISSUE THREAD

**Issue by danzam284** [zbot473/SurvivHacks#158]
Hey the auto aim is slow now and it does not work as well :(

**Comment by alexvornoffice** [comment]
agree +1

**Comment by BopItFreak** [comment]
aggree +2

**Comment by ALEXXANDRO23** [comment]
aggree +3

**Comment by wowthisiscool** [comment]
agreed

**Comment by zbot473** [comment]
I really am not sure why this is like that

**Comment by RuanTM** [comment]
really snipers are rarely fulfilling their goals, sad reality

**Comment by zbot473** [comment]
#101

**Comment by alexvornoffice** [comment]
5 vs 1? That person is not talking for all others. Should stay opened.

**Comment by zbot473** [comment]
@alexvornoffice does this still exist?
