### ISSUE TITLE
the hack stopped working

### ISSUE THREAD

**Issue by ALEXXANDRO23** [zbot473/SurvivHacks#159]
Could it be updated?

**Comment by zbot473** [comment]
read the console for something like error: variable not found or protocol mismatch

**Comment by theunleet** [comment]
I do believe it says net::ERR_BLOCKED_BY_CLIENT if that helps

**Comment by rosko1337** [comment]
> I do believe it says net::ERR_BLOCKED_BY_CLIENT if that helps, did they update something? Reinstall extension does nothing, protocolVersion change does nothing.

Error: playerbarn not defined

**Comment by zbot473** [comment]
@theunleet that is not relevant. Actual errors should say "cannot find ___ of undefined"
