### ISSUE TITLE
Disable autoaim if colision detected

### ISSUE THREAD

**Issue by alexvornoffice** [zbot473/SurvivHacks#160]
Disable auto aim if some tree or other object are between player an enemy - is present, so it will look less suspicious...

**Comment by alexvornoffice** [comment]
@zbot473 - can you submit a patch?

**Comment by Derpitu** [comment]
that is so smart!

**Comment by Derpitu** [comment]
lol

**Comment by zbot473** [comment]
That's pretty difficult tho

**Comment by zbot473** [comment]
I mean i can use the same things as the trigger bot

**Comment by alexvornoffice** [comment]
yeah

**Comment by alexvornoffice** [comment]
I added the code but I stuck don't know what to do next : https://github.com/zbot473/SurvivHacks/commit/ecfd4e3ae225013eb8a875b529e1b0222a5c19b7

**Comment by zbot473** [comment]
@alexvornoffice what does it do

**Comment by alexvornoffice** [comment]
> @alexvornoffice what does it do

Nothing, at the moment because the work is in progress.
Only adds to the console the info that collision detected or not detected.

**Comment by alexvornoffice** [comment]
Maybe you can take a look and continue finishing this feature.

**Comment by zbot473** [comment]
Ok

**Comment by ThanksMrSotarks** [comment]
@zbot473 make it as a toggleable feature, cus i still want to do the blatant cheater style

**Comment by alexvornoffice** [comment]
> @zbot473 make it as a toggleable feature, cus i still want to do the blatant cheater style

You can get banned, I saw someone on youtube got his account ban banned.

**Comment by zbot473** [comment]
@alexvornoffice in the future for somewhat big changes please create a pull request

**Comment by ThanksMrSotarks** [comment]
@zbot473 i can reupload the previous version as a pull request if you want to

**Comment by alexvornoffice** [comment]
> @zbot473 i can reupload the previous version as a pull request if you want to

And how this will help? this new thing is in beta, do download older version if you don't like... this needs testing and improvement... older version - https://github.com/zbot473/SurvivHacks/tree/e63962ee27bed94a5939580181b4b711abeba014

**Comment by alexvornoffice** [comment]
![beta-info](https://user-images.githubusercontent.com/1689187/50169594-8ea68980-02f6-11e9-8ec6-a182b909bbed.png)

**Comment by alexvornoffice** [comment]
WIP --  means work in progress, why people download latest version and say don't like, it is not finished, you are a tester, if I will pull requeste then how people will test??? and how will I find problems? I need people testing and telling me all their problems. Understand?
