### ISSUE TITLE
Auto loot doesn't work

### ISSUE THREAD

**Issue by colkat406** [zbot473/SurvivHacks#162]
Auto loot doesn't work

**Comment by theunleet** [comment]
As colkat406 says autoloot is now broken!

**Comment by alexvornoffice** [comment]
yes, I could not find autoloot variables, planes tracking broken too. No fix at the moment.

**Comment by theunleet** [comment]
Thanks, no problem will look around as well.

**Comment by zbot473** [comment]
Fixed
