### ISSUE TITLE
Toggle for vibrant bullets

### ISSUE THREAD

**Issue by asianhacks** [zbot473/SurvivHacks#163]
Sometimes the vibrant colors are a bit disturbing is it possible to make a switch to turn it off on the menu?

**Comment by zbot473** [comment]
There is (i think). Try going to the config section and it should be under barrel recolor

**Comment by asianhacks** [comment]
ok

**Comment by zbot473** [comment]
You have to reinstall extension (click remove and re add but you don't need to redownload)
