### ISSUE TITLE
Feature: Get enemy health

### ISSUE THREAD

**Issue by alexvornoffice** [zbot473/SurvivHacks#165]
Get from other browser window, for the same game, the enemy health that will be shared via extension to main window.
Pros: you will get health of one enemy until he dies then move to other player
Cons: the game can choose your player health, will not be able to see all other enemies health levels

I saw at the multibox branch that it is possible to share data between windows, so that's why I think this is possible.

**Comment by alexvornoffice** [comment]
not good idea :(

**Comment by zbot473** [comment]
What's the use of it?

**Comment by alexvornoffice** [comment]
I closed the ticket already

**Comment by zbot473** [comment]
k
