### ISSUE TITLE
the autoaim is somewhat confusing?

### ISSUE THREAD

**Issue by ALEXXANDRO23** [zbot473/SurvivHacks#166]
I like the new autoaim is more accurate thank you ..... But sometimes stop not recognizing my enemy and shoot towards nothing

**Comment by ALEXXANDRO23** [comment]
even if I have it close to me and it's a bit confusing sometimes it works perfection and then it gets confused

**Comment by alexvornoffice** [comment]
I detected bush and bridge problem, so bushes and bridges needs fixing.

**Comment by ALEXXANDRO23** [comment]
wow now I understand that for the autoaim to work I have to put the cursor on the enemy ..... could you make it work automatically as before?

**Comment by ALEXXANDRO23** [comment]
putting the cursor over the enemy makes it more suspicious the hack besides being annoying wing of shooting

**Comment by ArmaanTornow** [comment]
You dont need to put cursor on them for it to work dawg

**Comment by ALEXXANDRO23** [comment]
if I do not put the cursor on the enemy, the auto aim doesn't work

**Comment by alexvornoffice** [comment]
It is new auto aim with collision detection, if there is a wall or a tree/rock it does not aim at enemy, why you no read the changes log?

**Comment by alexvornoffice** [comment]
A toogle will fit nice, maybe @zbot473 will implement, I think he does not like my new patch, he should test it and he will like it. :D

**Comment by zbot473** [comment]
I will test lol

**Comment by ALEXXANDRO23** [comment]
@alexvornoffice Oh sure I understand, but I keep insisting that it is too obvious, when I fight with someone what I did was to deactivate / activate the z key was not always active the aimbot only activated it when I was fighting with someone

**Comment by ALEXXANDRO23** [comment]
it's weird that he shot the enemy and it goes through a tree and I have a shooting angle but the autoaim shoots at nothing or moves like crazy when there are several enemies nearby ... When the point is that it is not obvious that you bring tricks

**Comment by ALEXXANDRO23** [comment]
but it is also true that now it is more precise (Thanks for that)

**Comment by alexvornoffice** [comment]
Maybe to leave as it is and add trees, rocks, other object/elements to the list of **non-collidable** objects and if someone will hide below a rock or a tree to still aim at him...?
I think this feature is better then aiming at a building or at a steel container you can not destroy, I always hit buildings and I don't like it that's why I tried to implement this feature. Of course I see it needs fixing for bushed, and bridges, maybe I will find something else, maybe interior building walls that you can destroy...

**Comment by ALEXXANDRO23** [comment]
Exactly maybe the autoaim continues to work on things that can be destroyed, And be deactivated when something can not be destroyed (I hope to explain it explained well I speak Spanish normally)

**Comment by alexvornoffice** [comment]
I fixed now it does ignore destructible items so will not hit buildings and metal things, only what is possible to destroy...
