### ISSUE TITLE
Hack not working....

### ISSUE THREAD

**Issue by IME9** [zbot473/SurvivHacks#17]
**Describe the bug**
Error causing the hack to not load. This error make the entire hack impossible to use beside auto-loot and transparency. 

**Screenshots**
https://gyazo.com/ed6fdbb137e185196cc545e45af15310

Extension version : 1.0.7.3

**Comment by zbot473** [comment]
I was sleeping. Right now I am at school, so I can't really do much.

**Comment by zbot473** [comment]
ok its fixed. check my patch branch. if that works then ill commit to master
