### ISSUE TITLE
what update?

### ISSUE THREAD

**Issue by RuanTM** [zbot473/SurvivHacks#174]
update of the new version

**Comment by pxoss** [comment]
the devs have to work to update it, they cant just find it and whippity do and update

**Comment by alexvornoffice** [comment]
I like the new update, that desert update was very stupid, too many planes and high quality drops...

**Comment by pxoss** [comment]
lol changes opinion within 3 hours

**Comment by zbot473** [comment]
Lol

**Comment by zbot473** [comment]
Fixed
