### ISSUE TITLE
Game is freezing

### ISSUE THREAD

**Issue by colkat406** [zbot473/SurvivHacks#179]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
vendor.c9de893b.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.11e97af7.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tag.min.js:18 
    tag.min.js 1.2s ✰ SRV ✰      ads by http://www.adinplay.com/     
api.adinplay.com/libs/aiptag/assets/adsbygoogle.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pa.rxthdr.com/v3/c?publisherId=511f1c27-5069-466f-b2f8-d21b9da3b540&host=surviv.io:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adinplay-d.openx.net/w/1.0/arj?ju=http%3A%2F%2Fsurviv.io%2F%23&jr=&ch=UTF-8&res=1920x1080x24&ifr=false&tz=0&tws=1920x938&be=1&bc=hb_pb_2.1.5&dddid=6bee262c-ccc9-4be2-87b2-a5a629e89f0d&nocache=1545318861983&aus=300x250&divIds=surviv-io_300x250&auid=540165239&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
as.casalemedia.com/cygnus?s=254295&v=7.2&r=%7B%22id%22%3A%22339f58f7067dfe%22%2C%22imp%22%3A%5B%7B%22id%22%3A%224a15fbc251d47b%22%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A250%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254295%22%2C%22sid%22%3A%22300x250%22%7D%7D%5D%2C%22site%22%3A%7B%22page%22%3A%22http%3A%2F%2Fsurviv.io%2F%23%22%2C%22ref%22%3A%22%22%7D%2C%22ext%22%3A%7B%22source%22%3A%22prebid%22%7D%7D&ac=j&sd=1&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
hbopenbid.pubmatic.com/translator?source=prebid-client:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tag.1rx.io/rmp/79123/0/mvo?z=1r&domain=surviv.io&url=http%3A%2F%2Fsurviv.io%2F%23&title=surviv.io%20-%202d%20battle%20royale%20game&dsh=1080&dsw=1920&tz=0&dtype=2&flash=0&hbv=1.30%2C1.0.1&imp=surviv-io_300x250&w=300&h=250&floor=0&t=d&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
g2.gumgum.com/hbid/imp?si=20523&pi=3&gdprApplies=true&gdprConsent=null&vw=1920&vh=938&sw=1920&sh=1080&pu=http%3A%2F%2Fsurviv.io%2F%23&ce=true&dpr=1&jcsi=%5Bobject%20Object%5D&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ib.adnxs.com/ut/v3/prebid:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
imasdk.googleapis.com/js/sdkloader/ima3.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pa.rxthdr.com/v3/a?publisherId=511f1c27-5069-466f-b2f8-d21b9da3b540&host=surviv.io:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
integrator.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
integrator.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=3474755217626999&correlator=607120224562070&output=json_html&callback=googletag.impl.pubads.callbackProxy1&impl=fif&eid=21062456%2C21062576%2C21062819&vrg=285&guci=1.2.0.0.2.2.0.0&plat=1%3A32776%2C2%3A16809992&sc=0&sfv=1-0-31&iu=%2F421469808%2Fsurviv.io_300x250&sz=300x250&eri=1&cust_params=GS%3DNo&cookie_enabled=1&bc=7&abxe=1&lmt=1545254167&dt=1545318862294&dlt=1545318861491&idt=780&frm=20&biw=1920&bih=938&oid=3&adx=0&ady=0&adk=1289977631&uci=1&ifi=1&u_his=5&u_h=1080&u_w=1920&u_ah=1040&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=4&u_sd=1&flash=0&url=http%3A%2F%2Fsurviv.io%2F%23&dssz=17&icsg=8391359&std=0&vis=1&scr_x=0&scr_y=0&ga_vid=557451357.1544274599&ga_sid=1545318862&ga_hid=2145139054&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tpc.googlesyndication.com/safeframe/1-0-31/html/container.html:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
hbopenbid.pubmatic.com/translator?source=prebid-client:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM65:3694 Init system logger
VM65:3693 Used 196 / 255 item types
VM65:3693 Used 555 / 65535 map types
VM65:860 Object
VM65:861 Object
g2.gumgum.com/hbid/imp?si=20524&pi=3&gdprApplies=true&gdprConsent=null&vw=1920&vh=938&sw=1920&sh=1080&pu=http%3A%2F%2Fsurviv.io%2F%23&ce=true&dpr=1&jcsi=%5Bobject%20Object%5D&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tag.1rx.io/rmp/79123/0/mvo?z=1r&domain=surviv.io&url=http%3A%2F%2Fsurviv.io%2F%23&title=surviv.io%20-%202d%20battle%20royale%20game&dsh=1080&dsw=1920&tz=0&dtype=2&flash=0&hbv=1.30%2C1.0.1&imp=surviv-io_728x90&w=970%7C728&h=90%7C90&floor=0&t=d&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
as.casalemedia.com/cygnus?s=254671&v=7.2&r=%7B%22id%22%3A%22195cee79ddd659f%22%2C%22imp%22%3A%5B%7B%22id%22%3A%2220777aab7fc02d3%22%2C%22banner%22%3A%7B%22w%22%3A728%2C%22h%22%3A90%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254671%22%2C%22sid%22%3A%22728x90%22%7D%7D%2C%7B%22id%22%3A%2221a0713517cbe4c%22%2C%22banner%22%3A%7B%22w%22%3A970%2C%22h%22%3A90%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254671%22%2C%22sid%22%3A%22970x90%22%7D%7D%5D%2C%22site%22%3A%7B%22page%22%3A%22http%3A%2F%2Fsurviv.io%2F%23%22%2C%22ref%22%3A%22%22%7D%2C%22ext%22%3A%7B%22source%22%3A%22prebid%22%7D%7D&ac=j&sd=1&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adinplay-d.openx.net/w/1.0/arj?ju=http%3A%2F%2Fsurviv.io%2F%23&jr=&ch=UTF-8&res=1920x1080x24&ifr=false&tz=0&tws=1920x938&be=1&bc=hb_pb_2.1.5&dddid=cbfc5d37-6a37-47a3-a9f3-334279a63b4b&nocache=1545318862313&aus=970x90%2C728x90&divIds=surviv-io_728x90&auid=540165244&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ib.adnxs.com/ut/v3/prebid:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
bid.contextweb.com/header/ortb:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=3474755217626999&correlator=607120224562070&output=json_html&callback=googletag.impl.pubads.callbackProxy1&impl=fif&eid=21062456%2C21062576%2C21062819&vrg=285&guci=1.2.0.0.2.2.0.0&plat=1%3A32776%2C2%3A16809992&sc=0&sfv=1-0-31&iu=%2F421469808%2Fsurviv.io_300x250&sz=300x250&eri=1&cust_params=GS%3DNo&cookie_enabled=1&bc=7&abxe=1&lmt=1545254167&dt=1545318862294&dlt=1545318861491&idt=780&frm=20&biw=1920&bih=938&oid=3&adx=0&ady=0&adk=1289977631&uci=1&ifi=1&u_his=5&u_h=1080&u_w=1920&u_ah=1040&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=4&u_sd=1&flash=0&url=http%3A%2F%2Fsurviv.io%2F%23&dssz=17&icsg=8391359&std=0&vis=1&scr_x=0&scr_y=0&ga_vid=557451357.1544274599&ga_sid=1545318862&ga_hid=2145139054&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pa.rxthdr.com/v3/a?publisherId=511f1c27-5069-466f-b2f8-d21b9da3b540&host=surviv.io:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=3474755217626999&correlator=3322336488595557&output=json_html&callback=googletag.impl.pubads.callbackProxy2&impl=fif&eid=21062456%2C21062576%2C21062819&vrg=285&guci=1.2.0.0.2.2.0.0&plat=1%3A32776%2C2%3A16809992&sc=0&sfv=1-0-31&iu=%2F421469808%2Fsurviv.io_728x90&sz=970x90%7C728x90&eri=1&cust_params=GS%3DNo&cookie_enabled=1&bc=7&abxe=1&lmt=1545254167&dt=1545318862866&dlt=1545318861491&idt=780&frm=20&biw=1920&bih=938&oid=3&adx=0&ady=0&adk=129044436&uci=2&ifi=2&u_his=5&u_h=1080&u_w=1920&u_ah=1040&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=4&u_sd=1&flash=0&url=http%3A%2F%2Fsurviv.io%2F%23&dssz=22&icsg=176163519&std=0&vis=1&scr_x=0&scr_y=0&ga_vid=557451357.1544274599&ga_sid=1545318862&ga_hid=2145139054&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM65:3693 Load atlas gradient
VM65:3693 Load atlas shared
VM65:3693 Load atlas main
hbevents.1rx.io/audit?bidder_version=1.0.1.0&doc_type=Prebid%20Audit&doc_version=1&framed=0&placement_codes=surviv-io_728x90&placement_id=79123&popped=0&prebid_version=1.30.0&response_ms=542&url=http%3A%2F%2Fsurviv.io%2F%23:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
hbevents.1rx.io/audit?bidder_version=1.0.1.0&doc_type=Prebid%20Audit&doc_version=1&framed=0&placement_codes=surviv-io_300x250&placement_id=79123&popped=0&prebid_version=1.30.0&response_ms=113&url=http%3A%2F%2Fsurviv.io%2F%23:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM65:3693 Loaded texture assets/main-0-100-33a0b616.png
VM65:3693 Loaded texture assets/gradient-0-100-2f5ab023.png
VM65:3693 Loaded texture assets/shared-0-100-299c5017.png
VM65:3693 Loaded texture assets/shared-1-100-2711639a.png
VM65:3693 Loaded texture assets/shared-2-100-771e7e89.png
VM65:3694 Ping test results
VM65:3694 ----------------------------------------
VM65:3694 region eu zone   fra ping   0.025
VM65:3694 region eu zone   waw ping   0.041
VM65:3694 region na zone   sfo ping   9999
VM65:3694 region na zone   mia ping   9999
VM65:3694 region na zone   nyc ping   9999
VM65:3694 region na zone   chi ping   9999
VM65:3694 region sa zone   sao ping   9999
VM65:3694 region as zone   sgp ping   9999
VM65:3694 region as zone   nrt ping   9999
VM65:3694 region as zone   hkg ping   9999
VM65:3694 region as zone   kor ping   9999
VM65:3694 Ping test results
VM65:3694 ----------------------------------------
VM65:3694 region eu zone   fra ping   0.025
VM65:3694 region eu zone   waw ping   0.041
VM65:3694 region na zone   sfo ping   9999
VM65:3694 region na zone   mia ping   9999
VM65:3694 region na zone   nyc ping   9999
VM65:3694 region na zone   chi ping   9999
VM65:3694 region sa zone   sao ping   9999
VM65:3694 region as zone   sgp ping   9999
VM65:3694 region as zone   nrt ping   9999
VM65:3694 region as zone   hkg ping   9999
VM65:3694 region as zone   kor ping   9999
VM65:3693 Joining ws://209.250.255.122:444/play?gameId=c2aa3eec24b4ef6f531aa6071100db26
VM65:3693 Unload atlas main
VM65:3693 Load atlas snow
VM65:3693 Loaded texture assets/snow-0-100-25cb8dfb.png
3VM65:755 Storing options...
hbopenbid.pubmatic.com/translator?source=prebid-client:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tag.1rx.io/rmp/79123/0/mvo?z=1r&domain=surviv.io&url=http%3A%2F%2Fsurviv.io%2F%23&title=surviv.io%20-%202d%20battle%20royale%20game&dsh=1080&dsw=1920&tz=0&dtype=2&flash=0&hbv=1.30%2C1.0.1&imp=surviv-io_300x250_2&w=300%7C970%7C728%7C970&h=250%7C90%7C90%7C250&floor=0&t=d&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ib.adnxs.com/ut/v3/prebid:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adinplay-d.openx.net/w/1.0/arj?ju=http%3A%2F%2Fsurviv.io%2F%23&jr=&ch=UTF-8&res=1920x1080x24&ifr=false&tz=0&tws=1920x938&be=1&bc=hb_pb_2.1.5&dddid=2e5fcac0-812a-4a00-ae72-08cde1416966&nocache=1545318905188&aus=300x250%2C970x90%2C728x90%2C970x250&divIds=surviv-io_300x250_2&auid=540165240&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
g2.gumgum.com/hbid/imp?si=20534&pi=3&gdprApplies=true&gdprConsent=null&vw=1920&vh=938&sw=1920&sh=1080&pu=http%3A%2F%2Fsurviv.io%2F%23&ce=true&dpr=1&jcsi=%5Bobject%20Object%5D&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
as.casalemedia.com/cygnus?s=254832&v=7.2&r=%7B%22id%22%3A%224518d26ab06e9c9%22%2C%22imp%22%3A%5B%7B%22id%22%3A%2246d959d9ba7cd3a%22%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A250%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254832%22%2C%22sid%22%3A%22300x250%22%7D%7D%2C%7B%22id%22%3A%22475e49713f85458%22%2C%22banner%22%3A%7B%22w%22%3A970%2C%22h%22%3A250%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254832%22%2C%22sid%22%3A%22970x250%22%7D%7D%2C%7B%22id%22%3A%2248d22c08aa79c76%22%2C%22banner%22%3A%7B%22w%22%3A970%2C%22h%22%3A90%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254832%22%2C%22sid%22%3A%22970x90%22%7D%7D%2C%7B%22id%22%3A%224909181b0afa493%22%2C%22banner%22%3A%7B%22w%22%3A728%2C%22h%22%3A90%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254832%22%2C%22sid%22%3A%22728x90%22%7D%7D%5D%2C%22site%22%3A%7B%22page%22%3A%22http%3A%2F%2Fsurviv.io%2F%23%22%2C%22ref%22%3A%22%22%7D%2C%22ext%22%3A%7B%22source%22%3A%22prebid%22%7D%7D&ac=j&sd=1&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pa.rxthdr.com/v3/a?publisherId=511f1c27-5069-466f-b2f8-d21b9da3b540&host=surviv.io:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=3474755217626999&correlator=3972282558207507&output=json_html&callback=googletag.impl.pubads.callbackProxy3&impl=fif&eid=21062456%2C21062576%2C21062819&vrg=285&guci=1.2.0.0.2.2.0.0&plat=1%3A32776%2C2%3A32776&sc=0&sfv=1-0-31&iu=%2F421469808%2Fsurviv.io_300x250_2&sz=300x250%7C970x90%7C728x90%7C970x250&eri=1&cust_params=GS%3DNo&cookie_enabled=1&bc=7&abxe=1&lmt=1545254167&dt=1545318905239&dlt=1545318861491&idt=780&frm=20&biw=1920&bih=938&oid=3&adx=0&ady=0&adk=2311900585&uci=3&ifi=3&u_his=4&u_h=1080&u_w=1920&u_ah=1040&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=4&u_sd=1&flash=0&url=http%3A%2F%2Fsurviv.io%2F%23&dssz=23&icsg=713034431&std=0&vis=1&scr_x=0&scr_y=0&ga_vid=557451357.1544274599&ga_sid=1545318862&ga_hid=2145139054&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
as.casalemedia.com/cygnus?s=254295&v=7.2&r=%7B%22id%22%3A%2250be87864e483d1%22%2C%22imp%22%3A%5B%7B%22id%22%3A%22518d8da1b5da0e2%22%2C%22banner%22%3A%7B%22w%22%3A300%2C%22h%22%3A250%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254295%22%2C%22sid%22%3A%22300x250%22%7D%7D%5D%2C%22site%22%3A%7B%22page%22%3A%22http%3A%2F%2Fsurviv.io%2F%23%22%2C%22ref%22%3A%22%22%7D%2C%22ext%22%3A%7B%22source%22%3A%22prebid%22%7D%7D&ac=j&sd=1&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adinplay-d.openx.net/w/1.0/arj?ju=http%3A%2F%2Fsurviv.io%2F%23&jr=&ch=UTF-8&res=1920x1080x24&ifr=false&tz=0&tws=1920x938&be=1&bc=hb_pb_2.1.5&dddid=6bee262c-ccc9-4be2-87b2-a5a629e89f0d&nocache=1545318907988&aus=300x250&divIds=surviv-io_300x250&auid=540165239&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tag.1rx.io/rmp/79123/0/mvo?z=1r&domain=surviv.io&url=http%3A%2F%2Fsurviv.io%2F%23&title=surviv.io%20-%202d%20battle%20royale%20game&dsh=1080&dsw=1920&tz=0&dtype=2&flash=0&hbv=1.30%2C1.0.1&imp=surviv-io_300x250&w=300&h=250&floor=0&t=d&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
g2.gumgum.com/hbid/imp?si=20523&pi=3&gdprApplies=true&gdprConsent=null&vw=1920&vh=938&sw=1920&sh=1080&pu=http%3A%2F%2Fsurviv.io%2F%23&ce=true&dpr=1&jcsi=%5Bobject%20Object%5D&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ib.adnxs.com/ut/v3/prebid:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
hbopenbid.pubmatic.com/translator?source=prebid-client:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pa.rxthdr.com/v3/a?publisherId=511f1c27-5069-466f-b2f8-d21b9da3b540&host=surviv.io:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=3474755217626999&correlator=2350644148916636&output=json_html&callback=googletag.impl.pubads.callbackProxy4&impl=fif&eid=21062456%2C21062576%2C21062819&vrg=285&guci=1.2.0.0.2.2.0.0&plat=1%3A67108864%2C2%3A67108864&sc=0&sfv=1-0-31&iu=%2F421469808%2Fsurviv.io_300x250&sz=300x250&rc=1&eri=1&cust_params=GS%3DNo&cookie_enabled=1&bc=7&abxe=1&lmt=1545254167&dt=1545318908088&dlt=1545318861491&idt=780&frm=20&biw=1920&bih=938&oid=3&adx=0&ady=0&adk=1289977631&uci=4&ifi=4&u_his=4&u_h=1080&u_w=1920&u_ah=1040&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=4&u_sd=1&flash=0&url=http%3A%2F%2Fsurviv.io%2F%23&dssz=24&icsg=2860518079&std=0&vis=1&scr_x=0&scr_y=0&ga_vid=557451357.1544274599&ga_sid=1545318862&ga_hid=2145139054&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tag.1rx.io/rmp/79123/0/mvo?z=1r&domain=surviv.io&url=http%3A%2F%2Fsurviv.io%2F%23&title=surviv.io%20-%202d%20battle%20royale%20game&dsh=1080&dsw=1920&tz=0&dtype=2&flash=0&hbv=1.30%2C1.0.1&imp=surviv-io_728x90&w=970%7C728&h=90%7C90&floor=0&t=d&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ib.adnxs.com/ut/v3/prebid:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
g2.gumgum.com/hbid/imp?si=20524&pi=3&gdprApplies=true&gdprConsent=null&vw=1920&vh=938&sw=1920&sh=1080&pu=http%3A%2F%2Fsurviv.io%2F%23&ce=true&dpr=1&jcsi=%5Bobject%20Object%5D&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
hbopenbid.pubmatic.com/translator?source=prebid-client:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
adinplay-d.openx.net/w/1.0/arj?ju=http%3A%2F%2Fsurviv.io%2F%23&jr=&ch=UTF-8&res=1920x1080x24&ifr=false&tz=0&tws=1920x938&be=1&bc=hb_pb_2.1.5&dddid=cbfc5d37-6a37-47a3-a9f3-334279a63b4b&nocache=1545318908104&aus=970x90%2C728x90&divIds=surviv-io_728x90&auid=540165244&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
bid.contextweb.com/header/ortb:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
as.casalemedia.com/cygnus?s=254671&v=7.2&r=%7B%22id%22%3A%2274eea5cbd670586%22%2C%22imp%22%3A%5B%7B%22id%22%3A%227526a99bff74b95%22%2C%22banner%22%3A%7B%22w%22%3A728%2C%22h%22%3A90%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254671%22%2C%22sid%22%3A%22728x90%22%7D%7D%2C%7B%22id%22%3A%2276fd89fe6b0b949%22%2C%22banner%22%3A%7B%22w%22%3A970%2C%22h%22%3A90%2C%22topframe%22%3A1%7D%2C%22ext%22%3A%7B%22siteID%22%3A%22254671%22%2C%22sid%22%3A%22970x90%22%7D%7D%5D%2C%22site%22%3A%7B%22page%22%3A%22http%3A%2F%2Fsurviv.io%2F%23%22%2C%22ref%22%3A%22%22%7D%2C%22ext%22%3A%7B%22source%22%3A%22prebid%22%7D%7D&ac=j&sd=1&:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=3474755217626999&correlator=2350644148916636&output=json_html&callback=googletag.impl.pubads.callbackProxy4&impl=fif&eid=21062456%2C21062576%2C21062819&vrg=285&guci=1.2.0.0.2.2.0.0&plat=1%3A67108864%2C2%3A67108864&sc=0&sfv=1-0-31&iu=%2F421469808%2Fsurviv.io_300x250&sz=300x250&rc=1&eri=1&cust_params=GS%3DNo&cookie_enabled=1&bc=7&abxe=1&lmt=1545254167&dt=1545318908088&dlt=1545318861491&idt=780&frm=20&biw=1920&bih=938&oid=3&adx=0&ady=0&adk=1289977631&uci=4&ifi=4&u_his=4&u_h=1080&u_w=1920&u_ah=1040&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=4&u_sd=1&flash=0&url=http%3A%2F%2Fsurviv.io%2F%23&dssz=24&icsg=2860518079&std=0&vis=1&scr_x=0&scr_y=0&ga_vid=557451357.1544274599&ga_sid=1545318862&ga_hid=2145139054&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
pa.rxthdr.com/v3/a?publisherId=511f1c27-5069-466f-b2f8-d21b9da3b540&host=surviv.io:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=3474755217626999&correlator=1653021013615908&output=json_html&callback=googletag.impl.pubads.callbackProxy5&impl=fif&eid=21062456%2C21062576%2C21062819&vrg=285&guci=1.2.0.0.2.2.0.0&plat=1%3A67108864%2C2%3A67108864&sc=0&sfv=1-0-31&iu=%2F421469808%2Fsurviv.io_728x90&sz=970x90%7C728x90&rc=1&eri=1&cust_params=GS%3DNo&cookie_enabled=1&bc=7&abxe=1&lmt=1545254167&dt=1545318908147&dlt=1545318861491&idt=780&frm=20&biw=1920&bih=938&oid=3&adx=0&ady=0&adk=129044436&uci=5&ifi=5&u_his=4&u_h=1080&u_w=1920&u_ah=1040&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=4&u_sd=1&flash=0&url=http%3A%2F%2Fsurviv.io%2F%23&dssz=25&icsg=11450452671&std=0&vis=1&scr_x=0&scr_y=0&ga_vid=557451357.1544274599&ga_sid=1545318862&ga_hid=2145139054&fws=4:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM65:3694 Ping test results
VM65:3694 ----------------------------------------
VM65:3694 region eu zone   fra ping   0.025
VM65:3694 region eu zone   waw ping   0.041
VM65:3694 region na zone   sfo ping   9999
VM65:3694 region na zone   mia ping   9999
VM65:3694 region na zone   nyc ping   9999
VM65:3694 region na zone   chi ping   9999
VM65:3694 region sa zone   sao ping   9999
VM65:3694 region as zone   sgp ping   9999
VM65:3694 region as zone   nrt ping   9999
VM65:3694 region as zone   hkg ping   9999
VM65:3694 region as zone   kor ping   9999
VM65:3693 Joining ws://188.122.68.133:444/play?gameId=0d5ef81ec2d6dc664fb5adfdfa0b2cf1

This is what it sayes in console

**Comment by TheSatanicAngeI** [comment]
`net::ERR_BLOCKED_BY_CLIENT` is most likely your adblocker which leads me to assume you use Chrome. 

> VM65:3694 Ping test results
VM65:3694 ----------------------------------------
VM65:3694 region eu zone fra ping 0.025
VM65:3694 region eu zone waw ping 0.041
VM65:3694 region na zone sfo ping 9999
VM65:3694 region na zone mia ping 9999
VM65:3694 region na zone nyc ping 9999
VM65:3694 region na zone chi ping 9999
VM65:3694 region sa zone sao ping 9999
VM65:3694 region as zone sgp ping 9999
VM65:3694 region as zone nrt ping 9999
VM65:3694 region as zone hkg ping 9999
VM65:3694 region as zone kor ping 9999

What the hell?!

How is the ping so high ? Are you sure you aren't accidently set on the wrong region ?


Do you have proxy security enabled ? Or any kind of firewall thingy on your internet like a secure browsing ?

It could also be a cache error. If you erased your history recently sometimes pages don't load correctly afterwards.

Welp I can't help you more than this I have school stuff to do lol

**Comment by alexvornoffice** [comment]
I free too, hmm :(

**Comment by zbot473** [comment]
@TheSatanicAngeI that's the ping for the other servers that aren't connected

**Comment by zbot473** [comment]
@alexvornoffice please add a toggle to your code

**Comment by alexvornoffice** [comment]
@zbot473 can you add? It has nothing to do with freezing btw, I have no time to add, maybe if I will find...

**Comment by theunleet** [comment]
Confirm game is freezing!

**Comment by ALEXXANDRO23** [comment]
It is true

**Comment by zbot473** [comment]
No more freezing
