### ISSUE TITLE
**Unauthorized extension use detected**

### ISSUE THREAD

**Issue by ALEXXANDRO23** [zbot473/SurvivHacks#18]
the extension does not work mark error ... Could it be solved? :( .... Thank you @zbot473

**Comment by IME9** [comment]
@ALEXXANDRO23   That happened on this one too?

I just made a notice for surviv+ cheat.

I think they patched or updated the game not sure.

**Comment by Kalaborative** [comment]
@zbot473 it's a simple regular expression fix. [See my commit on the other extension](https://github.com/Kalaborative/survivio-plus/commit/91ea9c818e5e219453fdca0318af4a225f6fbcd7)

**Comment by zbot473** [comment]
I was sleeping. Right now I am at school, so I can't really do much.

**Comment by zbot473** [comment]
Check patch branch maybe it'll work

**Comment by ThanksMrSotarks** [comment]
background.js fix makes the extension work in the patch, but nullifies cheat. might have to tweak with init file

**Comment by zbot473** [comment]
@kalaborative apparently it broke the extension

**Comment by zbot473** [comment]
@ALEXXANDRO23 @IME9 should work now. check the patch branch

**Comment by zbot473** [comment]
@ThanksMrSotarks So in the future, try checking the js console in chrome devtools for errors, and try fixing the code there. That is a good way to learn.

**Comment by ThanksMrSotarks** [comment]
thanks, appreciate that.

**Comment by zbot473** [comment]
@ThanksMrSotarks does it work?

**Comment by ALEXXANDRO23** [comment]
now it works perfectly many thanks @zbot473  Great job

**Comment by zbot473** [comment]
Ok
