### ISSUE TITLE
Its keep on freezing mid-game 

### ISSUE THREAD

**Issue by SahilKing23** [zbot473/SurvivHacks#180]
[SurvivHacks-master.zip](https://github.com/zbot473/SurvivHacks/files/2699750/SurvivHacks-master.zip)

**Comment by theunleet** [comment]
Something with the update makes it freeze, sorry no idea how to fix it.

**Comment by ThanksMrSotarks** [comment]
might be that pesky transparency bug again, try putting the object, ceiling and smoke alphas to 1 in the config tab (access by pressing ESC) and test it out. @SahilKing23 @theunleet

**Comment by alexvornoffice** [comment]
Does it work?

**Comment by FallingBoi** [comment]
@ThanksMrSotarks @alexvornoffice Soesnt works teh transparency, its keep freezing i tried it.

**Comment by theunleet** [comment]
@ThanksMrSotarks  Yeah I tried that and some other stuff.... no dice, sometimes I make it entire game, most of the time freeze early on though.

**Comment by SahilKing23** [comment]
same

**Comment by TheSatanicAngeI** [comment]
It was working well yesterday, consider reverting ?

**Comment by zbot473** [comment]
Did someone back up game code yesterday?

**Comment by alexvornoffice** [comment]
18 December - http://surviv.io/js/app.93d196bb.js

**Comment by alexvornoffice** [comment]
Todar - http://surviv.io/js/app.11e97af7.js

**Comment by zbot473** [comment]
Cool

**Comment by zbot473** [comment]
Does the diff reveal anything? cant really do it rn

**Comment by zbot473** [comment]
I think he was lucky that one time the game didn't freeze but idk

**Comment by surviv314** [comment]
By the way, survivio-plus is still freezing?

**Comment by surviv314** [comment]
survivio-plus never freezes...

**Comment by wowthisiscool** [comment]
> By the way, survivio-plus is still freezing?

yeah surviv+ is freezing too now.

**Comment by zbot473** [comment]
No more freezing
