### ISSUE TITLE
How to decrease freezing?!

### ISSUE THREAD

**Issue by alexvornoffice** [zbot473/SurvivHacks#184]
First disable Auto-aim,
stop wining the round, go until second place and I think the freezing will decrease...
Give a try!

**Comment by WVVEY** [comment]
Um ok im still confused about what u mean

**Comment by WVVEY** [comment]
what do u mean
this is unclear
we need more clear instructions or maybe u guys can just fix the damn thing XD

**Comment by zbot473** [comment]
That's odd. I thought it was on a per game basis

**Comment by killercloudj** [comment]
Cant you use the code from one of the people that help you?

**Comment by killercloudj** [comment]
Like Kalaborative ?

**Comment by Exerciz** [comment]
I saw here many things about how to reduce the freeze but nothing here was helpfully.

And I found something out...
You just need to  set everything in Transparency on 1. Played yesterday 30-40 games without a crash. Have fun.

 And I don't know why the Developer here Zbot can't fix thise issues like he did always in some hours. It's now 5 days ago and the Hack is still not updated.

**Comment by zbot473** [comment]
I don't know/can't find the piece of code where it stops the websocket @Exerciz i spent like 10 hours on this :(

**Comment by alexvornoffice** [comment]
If you fix the cheat - later or sooner they will find out and increase anti-cheat levels, so it will be harder to fix it, so it will be a infinite war... the hack should be only for a few limited number of users...

**Comment by alexvornoffice** [comment]
@zbot473 how to replace this???
![how-to-update](https://user-images.githubusercontent.com/1689187/50424810-704f0980-0873-11e9-841b-78aa226d28e5.png)

**Comment by alexvornoffice** [comment]
I added [[FunctionLocation]] key in the top but I can not replace value from the bottom...

**Comment by zbot473** [comment]
@alexvornoffice talk to me on discord

**Comment by surviv314** [comment]
survivio-plus seems to never freeze...🤔

**Comment by wowthisiscool** [comment]
maybe you should ask kalaborative for help because his cheat doesn't freeze

**Comment by zbot473** [comment]
I am talking with him @wowthisiscoolwowthisiscool

**Comment by zbot473** [comment]
it only stops drawing. you can still move but you cannot see it. Now I know a direction to start working in

**Comment by wowthisiscool** [comment]
> it only stops drawing. you can still move but you cannot see it. Now I know a direction to start working in

good luck and thank you so much for working on this.

**Comment by Reeyaad** [comment]
The older version of cheat Extension 1.1.8 is not freezing with following modified config. 
Cheat was Downloaded on 12.27.2018
![image](https://user-images.githubusercontent.com/20893493/50618322-37223380-0f1c-11e9-831d-8d44c4626a1c.png)
![image](https://user-images.githubusercontent.com/20893493/50618329-40ab9b80-0f1c-11e9-8597-99d68a4968f1.png)
![image](https://user-images.githubusercontent.com/20893493/50618339-473a1300-0f1c-11e9-952c-838589ce0bbc.png)
![image](https://user-images.githubusercontent.com/20893493/50618343-4c975d80-0f1c-11e9-9045-181cfd275fb3.png)

**Comment by zbot473** [comment]
It's because there is no event
