### ISSUE TITLE
Discord link is expired

### ISSUE THREAD

**Issue by hdgrid** [zbot473/SurvivHacks#185]
Update it please.

**Comment by StabbyAlbert** [comment]
We just had a massive purge and deleted some links. Heres the new link

**Comment by oskar9991** [comment]
this link still don't work

**Comment by zbot473** [comment]
Really?

**Comment by oskar9991** [comment]
yep :/

**Comment by zbot473** [comment]
what does it say

**Comment by oskar9991** [comment]
Invite Invalid:
This invite may be expired, or you might not have permission to join.
