### ISSUE TITLE
WATCH OUT!!!

### ISSUE THREAD

**Issue by TheSatanicAngeI** [zbot473/SurvivHacks#186]
### YOU CAN ACTUALLY GET BANNED

_Yes this is not a joke look at the screenshots_

![oopsie](https://user-images.githubusercontent.com/19210871/50425564-a70f2a80-0847-11e9-9dfd-6faf296c47f8.jpg)

![doopsie](https://user-images.githubusercontent.com/19210871/50425566-b0989280-0847-11e9-814c-f9dc684d4703.jpg)

**Comment by wowthisiscool** [comment]
i think they dont track your ip so they cant ban you yet

**Comment by StabbyAlbert** [comment]
I actually got unban from the game, I dnt think they can do anything to ban u, cuz U can just use VPN

**Comment by Kalaborative** [comment]
just play without an account, or make a new one -- they *can* IP ban you from the site altogether though so you'd have to use VPN to get around that

**Comment by alexvornoffice** [comment]
that's why we need to make the cheat not look like you area cheating, I even added collision detection to the hack but aim looks suspicions anyway, but now the problem is the freezing... why it is freezing? @Kalaborative

**Comment by silentes** [comment]
Can we please delete this issue, this is retarded, you're literally feeding the devs.

**Comment by zbot473** [comment]
done
