### ISSUE TITLE
This thing is uplayable keeps freezing pls fix this

### ISSUE THREAD

**Issue by lololololool** [zbot473/SurvivHacks#190]
**Describe the bug**

**Screenshots**
Add photos of bugs from the console, if it is closely related to it.

**Desktop (please complete the following information):**
 - Browser version
 - Extension version [e.g. 1.0.70]

**Expected behavior**

**Additional context**

**Comment by zbot473** [comment]
what version

**Comment by FallingBoi** [comment]
@zbot473 This version is unplayable.
Keeps freezing, yesterday i used it and goes good, but today, freezing.

**Comment by theunleet** [comment]
Try solo mode, need to test some things....
