### ISSUE TITLE
FIX THE LAG

### ISSUE THREAD

**Issue by FallingBoi** [zbot473/SurvivHacks#191]
I have 200+ ping when i play and nobody is using internet, im northamerica server, im from México. Aned i have good internet connection, without hack its goes good, but with hack he fucking ping is over 300.

**Comment by heatfist** [comment]
Do you pay him to make the hack?

**Comment by FallingBoi** [comment]
@heatfist Do you pay my internet?

**Comment by zbot473** [comment]
no u

**Comment by zbot473** [comment]
@heatfist nope lol

**Comment by ArmaanTornow** [comment]
If its that play legit ya fucking pleb

**Comment by Reeyaad** [comment]
lol

**Comment by heatfist** [comment]
> @heatfist nope lol

LOL idk why that guy is such that lame. Like is he retarded or what? xD
