### ISSUE TITLE
Cannot use it on new game version 0.6.95

### ISSUE THREAD

**Issue by ALiangLiang** [zbot473/SurvivHacks#199]
**Describe the bug**
I can't use it on new game version `0.6.95`.

**Screenshots**
Just popup a error message `This extension can not work with this version of the game!`

**Desktop (please complete the following information):**
 - Browser version 71.0.3578.98
 - Extension version 1.0.741

**Expected behavior**
Work.

**Additional context**
I try to fixed it with exports object. But still stuck on launch a new game.
```

                var p = exports.ceee80d9.exports.Defs,
                    bullets = exports["989ad62a"].exports.bullets,
                    tracerColors = exports["989ad62a"].exports.tracerColors,
                    u = exports["989ad62a"].exports.player,
                    items = exports["989ad62a"].exports.items,
                    bagSizes = exports["989ad62a"].exports.bagSizes,
                    scopeZoomRadius = (exports["989ad62a"].exports.Input, exports["989ad62a"].exports.scopeZoomRadius.desktop),
                    protocolVersion = exports["989ad62a"].exports.protocolVersion,
                    y = exports.e5d16b4d.exports.tt, // here
                    playerbarn = exports.a508b62a.exports.De, // here
                    lootBarn = exports.a48f3bb2.exports.Ke, // here
                    bulletBarn = exports.c73dee75.exports.Oe, // here
                    uiModel = exports.d3da5587.exports.$e, // here
                    keys = exports["4b8d140f"].exports.Key;
```

And crush when I enable the `auto aim`, `auto loot` and `lines to players`. Disable them will be find.

**Comment by theunleet** [comment]
Needs update.

**Comment by ALiangLiang** [comment]
BTW. Is this project not release the "source" code? It's hard to fix it with obfuscated code.

**Comment by zbot473** [comment]
@ALiangLiang we started from PowerOfUniverse's code, and he wants $70 for the unobfuscated code
