### ISSUE TITLE
Hey ZBot

### ISSUE THREAD

**Issue by Exerciz** [zbot473/SurvivHacks#20]
I would really to chat with you private, if it's possible.
It's about the Surviv.io Hack which you now continue.. Could pay you a good price for your hard work . Would be nice if we could deal private. If you have Discord add me there. My Discord : Dread#7332

-Waiting

**Comment by alexvornoffice** [comment]
are you from surviv.io and want to close the cheat? :D

**Comment by ThanksMrSotarks** [comment]
*insert Ali-A theme here*

**Comment by zbot473** [comment]
No.
