### ISSUE TITLE
Hello ZBot

### ISSUE THREAD

**Issue by Exerciz** [zbot473/SurvivHacks#205]

**Comment by ArmaanTornow** [comment]
Glad you learned how dumb your question was before someone had to respond :)

**Comment by Exerciz** [comment]
@ArmaanTornow Dumb are you idiot. I just wrote him through Discord.

**Comment by alexvornoffice** [comment]
why you not using survivio-plus? - it's free, i saw a paid one with subscription on youtube made by ice hacks...

**Comment by alexvornoffice** [comment]
here is the link - https://www.youtube.com/watch?v=s9o2A6yU8YY the demo

**Comment by Exerciz** [comment]
@alexvornoffice I tested the survivio-plus and it's bad. About aim i would better say nothing..
I know that Ice made one and i bought it somedays ago but it's not like that one who made zbot..it hasn't a lot features which had zbot's one. You selling your's ? I saw that you made something similar zbot's one, would be great if we can write through discord or here if you are selling it or if i can just play with it to see how it's...

**Comment by BigQuantumMan** [comment]
@Exerciz 
I have a suggestion. Discord?
Merter # 9785

**Comment by Exerciz** [comment]
@BigQuantumMan

**Comment by alexvornoffice** [comment]
> @alexvornoffice I tested the survivio-plus and it's bad. About aim i would better say nothing..
> I know that Ice made one and i bought it somedays ago but it's not like that one who made zbot..it hasn't a lot features which had zbot's one. You selling your's ? I saw that you made something similar zbot's one, would be great if we can write through discord or here if you are selling it or if i can just play with it to see how it's...

Maybe I will give you to try my hack, give me your e-mail just in case, I need to improve aim a little more and do some other stuff... and the code will be obfuscated like a free trial... but if you want you can pay me a little money, but no if it's your parents money....

**Comment by Exerciz** [comment]
@alexvornoffice Sure. Email: ffff2_789@hotmail.com

**Comment by BigQuantumMan** [comment]
I will also finish the cheat soon.
I think I will make it public (on my github).
;)
![image](https://user-images.githubusercontent.com/49454024/56083610-a666c800-5e27-11e9-9efd-08c39ad61785.png)

**Comment by Exerciz** [comment]
@alexvornoffice Yes you can do it.. i got the updated version from zbot and playing with it now 2days everything fine.

**Comment by alexvornoffice** [comment]
if you are interested into my hack how it works - check out my youtube video - youtube.com/watch?v=X0IBWqMeVbM

**Comment by alexvornoffice** [comment]
Today I played alone quad mode, and once I did 24 kills :D

**Comment by alexvornoffice** [comment]
Other video in quad mode where I did won at the end - https://www.youtube.com/watch?v=E4qQs5mcMwI
So my cheat helps winning alone in quad mode :D

**Comment by zbot473** [comment]
I wish I had time for this repo

**Comment by BigQuantumMan** [comment]
https://github.com/BigQuantumMan/Surviv.io-Cheat

However, I make it public faster :)

**Comment by zbot473** [comment]
@BigQuantumMan 
Do you want to be a contributor of this repo?

**Comment by BigQuantumMan** [comment]
I will let you know, because I have a lot of responsibilities now ;)
But maybe if I have some more time...

**Comment by zbot473** [comment]
same lol
