### ISSUE TITLE
An offer

### ISSUE THREAD

**Issue by Exerciz** [zbot473/SurvivHacks#21]
..

**Comment by alexvornoffice** [comment]
You better contact Powerofuniverse he said he closed the cheat because no money is made...

> Unprofitable project (too big time requirements)

**Comment by Exerciz** [comment]
Can’t contact him because he archived his one..

**Comment by zbot473** [comment]
How can I even trust you tho

**Comment by alexvornoffice** [comment]
PowerOfUniverse email I think this is: damian.op@onet.eu

**Comment by Exerciz** [comment]
There is nothing to trust..
I just offered you to create an private one for him like this here..My budget is 500-600€. Just contact me through Discord or Email.
