### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ThanksMrSotarks** [zbot473/SurvivHacks#24]
if i were to open the js console to start fixing the cheat, do i open it in the main menu or straight out during ingame?

**Comment by ThanksMrSotarks** [comment]
also the new patch doesn't affect init.js i think, i put it in console and it returns with "false"

**Comment by zbot473** [comment]
It did. There were some changes in the obfuscation, although minor. The other thing that changed was the scopezoomradius variables in exports.
