### ISSUE TITLE
Autoswitch importance

### ISSUE THREAD

**Issue by zbot473** [zbot473/SurvivHacks#26]
Rank these in order of importance: (I am making an autoswitch script for this hack)
DPS 
Range
Accuracy (spread)
Bullet count per trigger pull
Obstacle Damage

**Comment by Kalaborative** [comment]
Range, Accuracy, DPS, bullet count, obstacle damage (my opinion)

**Comment by zbot473** [comment]
@ThanksMrSotarks @IME9 @asianhacks try the autoswitch by downloading the branch

**Comment by joy880828** [comment]
@zbot473  

May I share this post to 「HumphreyGaming YT DISCORD」?

So that your question can get more opinion.

**Comment by zbot473** [comment]
Sure

**Comment by joy880828** [comment]
@zbot473  OK, I will contact him.

**Comment by ThanksMrSotarks** [comment]
imma test the branch later today, will give feedback in half a day or less

**Comment by ThanksMrSotarks** [comment]
Needless to say, autoswitch works fine, however it feels annoying as it will opt out of a gun if it's empty, making reload nearly impossible for the secondary gun.

**Comment by ThanksMrSotarks** [comment]
@zbot473 might wanna put reloading as a higher priority than most of em ngl

**Comment by zbot473** [comment]
most of what @ThanksMrSotarks

**Comment by ThanksMrSotarks** [comment]
@zbot473 most of the other priorities
