### ISSUE TITLE
Can you create a surviv.io clone?

### ISSUE THREAD

**Issue by alexvornoffice** [zbot473/SurvivHacks#27]
It is possible to make a clone of the game on other domain with custom settings? 
Like less players or better guns, more bullets... etc

So anybody can set up the game they want, maybe make a tanks game instead? or additional game files required?

I think would be great someone to post the game source code as a project page here on github with instructions to make the game work and how to modify the game...

It will be very great to play modified versions of this game with tanks or new guns and maps, everybody could support or submit new guns or maps...

**Comment by zbot473** [comment]
Nope. I don't have access to the server side code.
