### ISSUE TITLE
I have some thinking about autoswitch

### ISSUE THREAD

**Issue by joy880828** [zbot473/SurvivHacks#29]
Hi , English is not my native language , so if I used rude or inappropriate words , please forgive me.

I think maybe you have tried this idea , if you really have  tried , please tell me the problems of this idea, maybe I can help.

Please see this image first : 

![image](https://user-images.githubusercontent.com/37370703/46583582-fedd9700-ca8b-11e8-9669-d6ce22a931b8.png)

Below I say distance 1 = that red line I marked in the image

So, is it possible to make a rank list , and we rank all weapons with all distance ?

I mean , if distance bewteen enemy and I is 0.5 , then MP220 will be absolutely better than AK-47 or M416.

But if distance is 4 , AK-47 or M416 will be better .

In this way we can make a range to switch weapon , for example : if distance is in 0 to 1.2 , maybe we can make a rank list like this :

AWM-S > MP220 > Vector > Saiga-12>................ ( this list will contain all weapons ) , so the script can decide which weapon is the best immediately.

This page has all weapon's data , maybe it will be helpful.

http://survivio.wikia.com/wiki/Weapons

**Comment by zbot473** [comment]
Actually, I take that all into account. If you read Rpref and Lpref, you can see the values. Also if the weapon is out of range, the pref value will become a very small negative number.
```
var RPref = (((gunR.bulletCount * bulletR.damage - Math.pow(distanceToEnemy, bulletR.falloff)) / gunR.fireDelay) / gunR.shotSpread),
    LPref = (((gunL.bulletCount * bulletL.damage - Math.pow(distanceToEnemy, bulletL.falloff)) / gunL.fireDelay) / gunL.shotSpread)
```
