### ISSUE TITLE
The game has been updated to version 0.6.0

### ISSUE THREAD

**Issue by IME9** [zbot473/SurvivHacks#3]
It says you modifed the game.js thingy 12 hours ago but I tried re-downloading, refreshing the extensions, disabling/enabling it notify me with "cannot work with this version of the game" and the page freeze.

pls fix <3

**Comment by IME9** [comment]
@zbot473  I downloaded the 0.6.0 version you updated and it still doesn't work...Do I have to load it unpacked or packed??? it still notify.
https://github.com/zbot473/SurvivHacks/tree/0.6.0-patch

For anyone who got the same issue this is the patch link

**Comment by IME9** [comment]
pls

**Comment by IME9** [comment]
@zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473 @zbot473

**Comment by zbot473** [comment]
@IME9 fixed. update
