### ISSUE TITLE
Aimbot-Keybind

### ISSUE THREAD

**Issue by Exerciz** [zbot473/SurvivHacks#32]
Hey,
What about to make Aim while shooting? Auto Aim is recognizable when someone is specating you..And it's annoying when you are in a house or somewhere to loot..it's always aiming on the enemy no matter what you do - hide/loot/afk..and it's bad. My idea is to make Keybind-for the Aim. Hope you can do it and it's not as hard as other things.

**Comment by zbot473** [comment]
Hold left Shift

**Comment by Exerciz** [comment]
I know it. To hold left shift is stupid. No one will hold left shift while runing, looting and and..
Just make it will help a lot people.

**Comment by zbot473** [comment]
so you mean a toggle?

**Comment by jialeyu** [comment]
Think he means like in Kalaborative's extension, having the aimbot only activate when pressing a key.

**Comment by Exerciz** [comment]
I mean if we could turn Auto Aim off and turn aim on by clicking left click on mouse would be nice.

**Comment by zbot473** [comment]
so only when shooting?

**Comment by Exerciz** [comment]
Yes

**Comment by Exerciz** [comment]
And the Hack is not working after your update.

**Comment by Exerciz** [comment]
Error in event handler for webRequest.onBeforeRequest/1: Error: Invalid value for argument 1. Value must not be less than 0.

**Comment by ThanksMrSotarks** [comment]
new patch came, will work on it in a few hours

**Comment by Exerciz** [comment]
The Auto-Switch is not the best idea it have some problems and i think people don't need it. Make Aim with Keybind please. Aim while shooting would be great.

**Comment by Exerciz** [comment]
Okay thanks
