### ISSUE TITLE
um the autofire dose not work

### ISSUE THREAD

**Issue by killercloudj** [zbot473/SurvivHacks#38]
**Describe the bug**
 When I hit my hit key it dose not work :( thats all i know
**Screenshots**
Add photos of bugs from the console, if it is closely related to it.

**Desktop (please complete the following information):**
 - Browser version
 - Extension version [e.g. 1.0.70]

**Expected behavior**

**Additional context**

**Comment by ThanksMrSotarks** [comment]
zbot is currently working on it, the issue is that since it's a bug in the extension itself, it's taking quite some time to patch it up, so please be patient

**Comment by zbot473** [comment]
fixed
