### ISSUE TITLE
Pick up things broken

### ISSUE THREAD

**Issue by FallingBoi** [zbot473/SurvivHacks#39]
Mhh... In the first game i can pick up everything, everything very good but when i die, or i win or i quit, qhen i start another game (For be exactly the 2nd game) i cant pick anything i need to reload the page and is very disturbing (SORRY FOR MY ENGLISH) When i start squad i need to wait like 10 secs for the hack works and get on.
Im very mad by this idk if is bcz i dont downloaded good the file or i installed it but can u fix it?

**Comment by RuanTM** [comment]
This also happens to me, I enter the first normal game without auto fire and auto loot because they are bugged, but in the second game the keys stop working, no key works ex: esc, m, w, a, s, d etc. .. if you can help!

**Comment by zbot473** [comment]
fixed
