### ISSUE TITLE
What about making it in a userscript?

### ISSUE THREAD

**Issue by IME9** [zbot473/SurvivHacks#4]
I've seen a japanese script that is working with the current version of surviv.io so it is possible for instance to use the aimbot section and make it a working userscript with tampermonkey? 

@zbot473

**Comment by ALEXXANDRO23** [comment]
@IME9 Do you think you can put in development some simple hack like the previous ones?

**Comment by ALEXXANDRO23** [comment]
The aimbot of now is a bit mmm......bad

**Comment by IME9** [comment]
@ALEXXANDRO23  Well I sadly have nothing working at the moment due to patch 0.6.0 

wait are you saying you have something working still?

**Comment by ALEXXANDRO23** [comment]
No, I'm just another user who was looking for a simpler hack, but if you are interested in doing some development of a hack, you can contac @PowerOfUniverse

**Comment by zbot473** [comment]
Why a userscript?

**Comment by IceHacks** [comment]
Userscripts can not accomplish as much, as easy as an extension can.
