### ISSUE TITLE
 In the second game the keys do not work

### ISSUE THREAD

**Issue by RuanTM** [zbot473/SurvivHacks#40]
I know you're giving your all to fix all the bugs and support what you do to society with nothing in return!

come on! when I enter the first normal start everything working except the auto fire and the auto loot as everyone already knows, but when I die in the first match and enter the second no key works, I do not even have to regenerate the site to work again , I think not everyone is experiencing such a bug more if they have concert! S2

**Comment by FallingBoi** [comment]
I have the same problem, its very bad im mad xd.
But thx to zbot for revive this beatiful hack. <3

**Comment by zbot473** [comment]
its fixed
