### ISSUE TITLE
Squad mode was updated.

### ISSUE THREAD

**Issue by IceHacks** [zbot473/SurvivHacks#41]
The Squad woods update has came. I don't know if it effects Duos and Solos. (edit) it does

**Comment by ThanksMrSotarks** [comment]
back to the drawing boards then.

**Comment by ArmaanTornow** [comment]
Im pretty sure Zbot has baisically stopped working on this code he got bored.

**Comment by Kalaborative** [comment]
I added a PR which should work for the current update. just wait for merge

**Comment by zbot473** [comment]
i fixed it welp

**Comment by zbot473** [comment]
@Kalaborative why is the bump fire code so complicated? i was able to accomplish it with just setInterval and mousedown/up events.
