### ISSUE TITLE
STREAMER MODE PLS!!!!!!

### ISSUE THREAD

**Issue by asianhacks** [zbot473/SurvivHacks#43]
I neeeed Streamer MODE!!!!!! is it possible? Can you teach me how to get rid of certain things?

**Comment by alexvornoffice** [comment]
I think it is needed some patches to make certain things work, so changing options is not enough..
You can remove lines so they will not show but gun position to the other players that looks suspicions needs some updates... Like aiming only when pressing mouse button or a special key, people always ask for help and for new features but very little help with patches...

**Comment by ArmaanTornow** [comment]
Also hacking on stream to make urself look good is kinda fucking gay

**Comment by asianhacks** [comment]
I mean its true but its pretty cool to be cheating but look liek ur not at the same time.
ps. @ArmaanTornow u dont gotta be so salty if u suck at surviv even with the hax (lol cant tell if ur sarcastic)

**Comment by ArmaanTornow** [comment]
@asianhacks well it looks like i got my main man zbots approval so gl getting a UI update fam

**Comment by ThanksMrSotarks** [comment]
yea that's gonna be a big fat L from me dawg.

**Comment by zbot473** [comment]
@asianhacks I am working on one now. I just need to iron out some bugs
