### ISSUE TITLE
Bug? i dont know

### ISSUE THREAD

**Issue by killercloudj** [zbot473/SurvivHacks#46]
**Describe the bug**
It crash everytime i go in a game 
**Screenshots**
![screenshot 51](https://user-images.githubusercontent.com/38992642/47754808-7ad59400-dc72-11e8-9a39-5fb246d5c2ca.png)

**Comment by alexvornoffice** [comment]
for me the same, try duo mode - should work fine

**Comment by killercloudj** [comment]
but i want to carry lots of people :(

**Comment by alexvornoffice** [comment]
I don't know, I tried several things and nothing, I don't even know what makes the game freeze...

**Comment by killercloudj** [comment]
:(

**Comment by merelymemeulous** [comment]
:(

**Comment by merelymemeulous** [comment]
Its still broken

**Comment by overgdbg** [comment]
:(

**Comment by killercloudj** [comment]
Thanks for making this for us :)

**Comment by merelymemeulous** [comment]
Yes thank the owners I'm just a admin!

**Comment by ThanksMrSotarks** [comment]
fixed
