### ISSUE TITLE
game doesn't start when i click play

### ISSUE THREAD

**Issue by colkat406** [zbot473/SurvivHacks#52]
![image](https://user-images.githubusercontent.com/36088507/47863682-b8abf700-ddef-11e8-8aa0-2dfd65b24a43.png)

i took a screenshot of the errors

hope u can fix it soon

**Comment by ThanksMrSotarks** [comment]
changing vars rn

**Comment by zbot473** [comment]
This is normal, the extension blocks the requests

**Comment by colkat406** [comment]
oh ok thanks
