### ISSUE TITLE
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by merelymemeulous** [zbot473/SurvivHacks#56]
**Describe the bug**
This keeps popping up 
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Screenshots**
Sorry cant get screen shots

**Desktop (please complete the following information):**
 - Chrome Mac os version 64 bit
 - Version 70.0.3538.77 (Official Build) (64-bit)

**Expected behavior**
I want to press start but it just blanks and doesn't respond

**Additional context**
No additional context just 
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by Derpitu** [comment]
plz try to get screenshots!!

**Comment by zbot473** [comment]
It's working. Reload the page
