### ISSUE TITLE
Error: Version

### ISSUE THREAD

**Issue by R2nR2n** [zbot473/SurvivHacks#58]
With the new update on the squad mode, the extension now gives an error saying outdated version, possibly fix this?

**Comment by ALEXXANDRO23** [comment]
Yes, could it be fixed? @zbot473  :C

**Comment by FallingBoi** [comment]
Same problem boi
;(

**Comment by killercloudj** [comment]
![screenshot 52](https://user-images.githubusercontent.com/38992642/48291889-06ef7480-e446-11e8-9228-0992b7bebfc6.png)

**Comment by killercloudj** [comment]
They need something to work out of so 
i did this

**Comment by killercloudj** [comment]
Thank you

**Comment by zbot473** [comment]
It won't work on squads

**Comment by zbot473** [comment]
Also I'm trying to fix the "use of an unauthorized extension" thing

**Comment by alexvornoffice** [comment]
Maybe to contact PowerOfUniverse? XD

**Comment by killercloudj** [comment]
Feels bad

**Comment by killercloudj** [comment]
UM i found a glich
![screenshot 54](https://user-images.githubusercontent.com/38992642/48294025-e0ced200-e44f-11e8-80a4-45b50e784d54.png)

**Comment by killercloudj** [comment]
It let me more for a little after it stop working and then it stoped

**Comment by killercloudj** [comment]
![screenshot 55](https://user-images.githubusercontent.com/38992642/48294217-ed9ff580-e450-11e8-866b-95796cc86d03.png)

**Comment by FallingBoi** [comment]
It crashes @zbot473

**Comment by killercloudj** [comment]
If someone teaches me how to code i will help

**Comment by FallingBoi** [comment]
i want to know how to code to make cheats ;( but i cant :,v

**Comment by FallingBoi** [comment]
@killercloudj add me on discord... FallingDown#2740

**Comment by zbot473** [comment]
Yeah, I know that.

**Comment by zbot473** [comment]
By using dom breakpoints, i found the function that writes unauthorized extension to the page. It's on line 3666 in app.js 
```   
 function i(e) {
    _.storeGeneric("error", "error"), _.enabled = !1, e && e.ws && e.ws.close();
    var t = document.body;
    if (t) {
        for (; t.firstChild;) t.removeChild(t.firstChild);
        r(t)
    }
}

function r(e) {
    for (var t = function(e) {
            return e.map(function(e) {
                return String.fromCharCode(e)
            }).join("")
        }, a = [60, 100, 105, 118, 47, 62], i = [85, 110, 97, 117, 116, 104, 111, 114, 105, 122, 101, 100, 32, 101, 120, 116, 101, 110, 115, 105, 111, 110, 32, 117, 115, 101, 32, 100, 101, 116, 101, 99, 116, 101, 100], r = [
            [109, 97, 114, 103, 105, 110, 84, 111, 112],
            [49, 48, 37],
            [116, 101, 120, 116, 65, 108, 105, 103, 110],
            [99, 101, 110, 116, 101, 114]
        ], o = f(t(a), {
            text: t(i)
        }), n = 0; n < r.length; n += 2) o.css(t(r[n + 0]), t(r[n + 1]));
    e.appendChild(o[0])
}
```

**Comment by zbot473** [comment]
Kalaborative already fixed it tho

**Comment by FallingBoi** [comment]
@zbot473 But it always crashes, if i know to code maybe i can help u, but idk xd
U think u can fin the problem in the code and repair them?

**Comment by RuanTM** [comment]
this also happens to me, I enter the match I start to play and out of nowhere everything hangs, only the sounds of the game can help me?

**Comment by RuanTM** [comment]
It's 2 att you're so

**Comment by FallingBoi** [comment]
@RuanTM Is a problem in the code, u only can play in solo-duo, squads doesnt works :(

**Comment by zbot473** [comment]
@FallingBoi it isn't a problem, but the game stops drawing to canvas after it freezes
