### ISSUE TITLE
the game keeps on freezing

### ISSUE THREAD

**Issue by colkat406** [zbot473/SurvivHacks#59]
**Describe the bug**

**Screenshots**
Add photos of bugs from the console, if it is closely related to it.

**Desktop (please complete the following information):**
 - Browser version
 - Extension version [e.g. 1.0.70]

**Expected behavior**

**Additional context**

**Comment by FallingBoi** [comment]
lol, it only freezes in Squad try it in Solo and duo.
We have only that :(

**Comment by ALEXXANDRO23** [comment]
:(

**Comment by colkat406** [comment]
oh ok
but it still sucks that it don't work in squad since it is limited edtion of squad

**Comment by killercloudj** [comment]
Feels bad
