### ISSUE TITLE
Why does surviv.io keep freezing when I play squad?

### ISSUE THREAD

**Issue by Baboylol** [zbot473/SurvivHacks#61]
**Describe the bug**
idk why but fk why its freezing while i using hax in squad now?
i need to fix this and play D:

**Screenshots**
Add photos of bugs from the console, if it is closely related to it.

**Desktop (please complete the following information):**
 - Browser version
 - Extension version 1.0.77

**Expected behavior**

**Additional context**

**Comment by alexvornoffice** [comment]
It freezes because it's a known bug that can not be fixed. 
It is like an error, external extension function detected.

**Comment by alexvornoffice** [comment]
This was asked 100 times already. :100:

**Comment by killercloudj** [comment]
@everyone

**Comment by zbot473** [comment]
this isn't discord man

**Comment by zbot473** [comment]
Also you typed that in lol

**Comment by killercloudj** [comment]
:(

**Comment by killercloudj** [comment]
Btw it dose not work still

**Comment by killercloudj** [comment]
Yeah it still dose not work

**Comment by zbot473** [comment]
I fixed it but it still won't work for squads.

**Comment by killercloudj** [comment]
Nope

**Comment by killercloudj** [comment]
i just went into one :(

**Comment by FallingBoi** [comment]
@zbot473 What u fixed boi?
Its seems everything same :/

**Comment by FallingBoi** [comment]
@IME9 Oh, sorry idk that :( im not a coder and my native language is the spanish so i dont understand so much.

**Comment by zbot473** [comment]
@IME9 Thank you for understanding

**Comment by zbot473** [comment]
@FallingBoi they patched the entire extension so i had to fix that

**Comment by ThanksMrSotarks** [comment]
yea so that's that, the game turned back to the regular non event version so expect an update within the day
