### ISSUE TITLE
How do I deobfuscate code?

### ISSUE THREAD

**Issue by ThanksMrSotarks** [zbot473/SurvivHacks#62]
Update: This was at first a help issue but since I've learned the basics I'm turning this into an additional vars deobfuscation guide
Credits to @Kalaborative for creating [this guide](https://docs.google.com/document/d/1idtE-KksJlafgGp97jggGjSGZmRAGgVEYAATAugfE2g/edit), highly recommend his python code, makes work way faster and easier
Extra information to know when deobfuscating
remember to delete the two "//" at the front of console.log in the init.js file before refreshing to check exports vars
![image](https://user-images.githubusercontent.com/43581418/48424350-144b7e00-e728-11e8-8bf0-b7fc77113dbd.png)
the exports info will be in the Console tab -> User messages

**Comment by killercloudj** [comment]
Um the other update came out

**Comment by zbot473** [comment]
Today?

**Comment by zbot473** [comment]
:/

**Comment by killercloudj** [comment]
When was the update?
