### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by R2nR2n** [zbot473/SurvivHacks#63]
Literally a new update, love the hack, please update it asap <3

**Comment by FallingBoi** [comment]
:u

**Comment by killercloudj** [comment]
He knows i told him befor

**Comment by killercloudj** [comment]
Can someone add me on discored to tell me when its out
@killercloudj#2459

**Comment by zbot473** [comment]
:(

**Comment by IME9** [comment]
@zbot473  :question:

**Comment by YESS808** [comment]
<3 thanks for all your work keep it up!

**Comment by zbot473** [comment]
Does it work now?

**Comment by zbot473** [comment]
Fixed
