### ISSUE TITLE
Character frozen

### ISSUE THREAD

**Issue by Jwnw1234** [zbot473/SurvivHacks#68]
Whenever I enter the game, my character is frozen and I can't move. The player count goes up when people join, but whatever i press, nothing happens. Please help!   I did the auto-update thing and also updated to the newest version.

**Comment by killercloudj** [comment]
Its working fine for me.....?

**Comment by zbot473** [comment]
auto update is kinda beta. Just redownload

**Comment by YESS808** [comment]
I'm having same issue where my character does not move, I've re downloaded the master.zip and unpacked it, re enabled it, still can't move.

**Comment by zbot473** [comment]
Ok

**Comment by zbot473** [comment]
Fixed
