### ISSUE TITLE
Unobfuscated code

### ISSUE THREAD

**Issue by zbot473** [zbot473/SurvivHacks#7]
@PowerOfUniverse Hey, can you send me the unobfuscated code? I will continue development

**Comment by zbot473** [comment]
@PowerOfUniverse I can keep going on with the project, just send me the code

**Comment by alexvornoffice** [comment]
Hi! How to get the new cheat? He archived the page now I think no more hacks...?!

**Comment by alexvornoffice** [comment]
So what application you are using to diff the code? I may try too but I need tools..

**Comment by alexvornoffice** [comment]
Basically it is required to edit only 2 files, init.js and app.js, app is the copy of the original game I think and and init.js is just extension file. Both needs to get modified ...

**Comment by alexvornoffice** [comment]
Do you know what diff aplication PowerOfUniverse was using?

**Comment by zbot473** [comment]
They are obfuscated. I can't really do anything.

**Comment by zbot473** [comment]
I use vs code

**Comment by alexvornoffice** [comment]
Do you mean minified? You can unminify the code: unminify.com but I don't know if it will work with big files...

**Comment by PowerOfUniverse** [comment]
@zbot473 
Forgive me, but I will not make my code available for free. Maybe I'll come back to it one day.

**Comment by ArmaanTornow** [comment]
@PowerOfUniverse If not for free than at what cost?

**Comment by PowerOfUniverse** [comment]
@ArmaanTornow 
The cost of the source code is 70 €.

The extension is compatible with the latest version of surviv.io.

**Comment by ArmaanTornow** [comment]
@PowerOfUniverse Who would i send money to and also is it updaed for pactches or will i have to do that?

**Comment by PowerOfUniverse** [comment]
At the moment everything works with version 0.6.21(condition from 17/10/2018).
The upgrade process is also very simple. It has a partial update system.
You should update only a few variables yourself when the new version surviv.io (I will add information about how to do it).

If you have more questions:
discord: damianop5 # 5293

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/47109041-81fdaa80-d24d-11e8-9489-382875d08ed2.png)
Only variables with comments need to be updated.

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/47110315-bfb00280-d250-11e8-841a-b0e42c5b0555.png)
This is one of the plugins (for example).

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/47110391-f71eaf00-d250-11e8-9eee-1f0f90fbf043.png)
This is one of the plugins (for example).

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/47110541-71e7ca00-d251-11e8-825f-f6fd2ac832b7.png)
This is one of the plugins (for example).

**Comment by zbot473** [comment]
the functions are what im asking about

**Comment by PowerOfUniverse** [comment]
@zbot473
The code has been rewritten and is different from the one made available on github. Everything has been converted into classes and separate modules. It's only possible to buy it, but that's it.
![image](https://user-images.githubusercontent.com/42821489/47309194-17c17d00-d634-11e8-90b4-df2a2b06fdfd.png)
