### ISSUE TITLE
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuto-update doesn't work???

### ISSUE THREAD

**Issue by IME9** [zbot473/SurvivHacks#71]
fuck all this bio bullshit

Problem : Notification asking to update with the script thingy I did and refreshed page. The message still appears so  I tried updating, removing and re adding with unpacked as usual developer mode blablabla still the same notification.

So I think the auto-update is broken :v

**Comment by zbot473** [comment]
i fixed it an hour ago

**Comment by zbot473** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA?
bio?

**Comment by zbot473** [comment]
Ok
