### ISSUE TITLE
Guns nerfed when using cheat?!

### ISSUE THREAD

**Issue by alexvornoffice** [zbot473/SurvivHacks#72]
It seems the hit damage is lower when using cheat.
Did somebody noticed this too?

I will do some research but I can tell 100% something exists... 
If you have some ideas how to check if hit damage is changed, when: 
1. cheat disabled OR
2. using other IP address maybe it is related to my IP address...

I would like to listen you ideas....
I will post update soon about my research...

**Comment by zbot473** [comment]
I will have a look into this.

**Comment by alexvornoffice** [comment]
So my first approach was to shot trees in different modes: cheat enabled/disabled and other IP address:
Could not find any difference in damage given to trees for different weapons, but I am still suspicious maybe it is related to players only, will look more into this... later.

**Comment by alexvornoffice** [comment]
My result so far:

How many hits until to kill one tree |   |  
-- | -- | --
GUNS LIST | With Cheat | With No Cheat | other IP address
G13C | 20 | 20 |  
MP5 | 16 | 17 |  
OT-38 | 7 | 7 | 7
UMP9 | 12 |   |  
M9 | 15 | 15 | 15
M416 |   | 17 |  
MAC-10 | 20 | 20 | 20
M93R | 15 | 15 |  
Deagle 50 |   |   |

**Comment by alexvornoffice** [comment]
I will add in future...

**Comment by alexvornoffice** [comment]
Just now I did 3 hits with AWM-S to kill one guy, is'n this suspicions? But I die from one shot with armor...

**Comment by ThanksMrSotarks** [comment]
@alexvornoffice the shots weren't recorded client-side is what I'm suspecting, having a live multiplayer game for browser isn't a good option after all.
