### ISSUE TITLE
I think the hack stopped working.

### ISSUE THREAD

**Issue by ALEXXANDRO23** [zbot473/SurvivHacks#79]
I do not see any of the functions of the hack just the transparency of the map, someone else happens or just me? :(

**Comment by zbot473** [comment]
Yup

**Comment by zbot473** [comment]
I shouldn't have renamed it :(

**Comment by zbot473** [comment]
now i have to refactor

**Comment by ALEXXANDRO23** [comment]
ok thank you very much for answering @zbot473 :)

**Comment by RuanTM** [comment]
hm,, comigo a mesma coisa alex mais o bot ja esta refatorando

**Comment by zbot473** [comment]
Actually, they've blocked console.logging somehow

**Comment by RuanTM** [comment]
So does it mean the end of the best hack to survive? ;

**Comment by zbot473** [comment]
No, i just need to patch that piece of code. I found what it did

**Comment by RuanTM** [comment]
UFA :D

**Comment by RuanTM** [comment]
even today the hack is ready for execution?

**Comment by zbot473** [comment]
Possibly

**Comment by RuanTM** [comment]
thanks <3

**Comment by zbot473** [comment]
alright, i fixed console logging

**Comment by zbot473** [comment]
Fixed!

**Comment by zbot473** [comment]
It was pretty easy after logging

**Comment by zbot473** [comment]
@RuanTM @ALEXXANDRO23 Fixed!!

**Comment by RuanTM** [comment]
aaa thanks kkk was playing without a hack here i saw a hack squad there i told zbot must have fixed s2
