### ISSUE TITLE
the hack has been patched D: 

### ISSUE THREAD

**Issue by ALEXXANDRO23** [zbot473/SurvivHacks#8]
Could it be fixed? :/

**Comment by zbot473** [comment]
Im trying to talk to the other guy who had the hack but idk

**Comment by ALEXXANDRO23** [comment]
you can contact @kalaborative, he also works in a hack, but it is of poor quality for my taste, but he is the only one who has it in operation, maybe he can help you.

**Comment by ALEXXANDRO23** [comment]
No :(

**Comment by Kalaborative** [comment]
@zbot473 Should be all good to go now

**Comment by zbot473** [comment]
@Kalaborative what do you mean?
