### ISSUE TITLE
Game updated to 0.6.6, tool no longer works.

### ISSUE THREAD

**Issue by YESS808** [zbot473/SurvivHacks#81]
**Describe the bug**
Game updated to 0.6.6, red block in lower right says extension will not work with this version of the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/19418185/48762129-3892e780-ec5f-11e8-87de-9f7feb019683.png)

**Desktop (please complete the following information):**
 - Browser version 70.0.3538.102 (Official Build) (64-bit)
 - Extension version 1.0.777

**Comment by alexvornoffice** [comment]
try to replaces variables... i can give document file with instructions...

**Comment by alexvornoffice** [comment]
https://docs.google.com/document/d/1idtE-KksJlafgGp97jggGjSGZmRAGgVEYAATAugfE2g/edit?usp=sharing

**Comment by alexvornoffice** [comment]
I tried myself to replace all init variables but no success, I think it is something more...

**Comment by alexvornoffice** [comment]
```
        e.exports = {
            menu: "we", 
            camera: "N",
            bullets: "Ee",
            planes: "Ne",
            activeId: "me",
            targetZoom: "f",
            objectCreator: "lt",
            pieTimer: "Ye",
            map: "Ce",
            input: {
                main: "ye",
                input: "input",
                mousePressed: "$"
            },
            activePlayer: {
                main: "mt",
                netData: "q",
                localData: "U"
            },
            playerBarn: {
                main: "Ie",
                players: "At"
            },
            lootBarn: {
                main: "He",
                itemf: "Pt",
                lootPool: "rt",
                pool: "de"
            },
            version: "1.0.777",
            protocolVersion: 39
        }
```

**Comment by alexvornoffice** [comment]
https://github.com/alexvornoffice/SurvivHacks you can check my fix

**Comment by zbot473** [comment]
Ah, I didn't realize you committed
sorry.
