### ISSUE TITLE
0.6.1 PATCHED

### ISSUE THREAD

**Issue by asianhacks** [zbot473/SurvivHacks#9]
NEED UPDATE already updated to 0.6.1!!!

**Comment by zbot473** [comment]
ill try but no promises

**Comment by Kalaborative** [comment]
@asianhacks  0.6.1 literally did nothing but remove the air drop spam lol

**Comment by zbot473** [comment]
@Kalaborative can you try and un-obfuscate the code

**Comment by Kalaborative** [comment]
The format with the separated modules would've been easier to work with .-. 

I'll try to deobfuscate what I can but it's still going to be hard to understand how everything is working

**Comment by zbot473** [comment]
@Kalaborative the thing is, there was more added

**Comment by zbot473** [comment]
@asianhacks fixed. please update.
