### ISSUE TITLE
Does anyone use right click to switch weapons?

### ISSUE THREAD

**Issue by zbot473** [zbot473/SurvivHacks#94]
I might replace the functionality with an autoaim toggle

**Comment by YESS808** [comment]
I use number keys to switch usually, but yeah I think a aim-on-rightClick would not be a terrible option.

**Comment by zbot473** [comment]
I finished it the basic code (it works) but i still need to make ui toggles

**Comment by RuanTM** [comment]
How to improve the aimbot? today I saw a very absurd sniper hack, I went to see his stats he has 3k wins, in short, has it to improve the aimbot?

**Comment by zbot473** [comment]
Try turning down the smooth level @RuanTM

**Comment by RuanTM** [comment]
https://prnt.sc/lm9qlx ja 
reduce but still it does not look so good and I do not have net lag

**Comment by zbot473** [comment]
I can't do anything about lag. sorry.

**Comment by zbot473** [comment]
@RuanTM Please make a new issue, as your comments are not related to this one.

**Comment by IME9** [comment]
KNGETWQOIJHWIUHTIUQHTWQ  OMG YES NO MORE OBVIOUS AIMING LOL

**Comment by joy880828** [comment]
I just download new hack , and I found I can't switch weapon with right click, so I come here , but u have post this issue XD

I am really  used to using right click to switch weapon, if possible ,please cancel this change.

**Comment by zbot473** [comment]
Im making a toggle

**Comment by ALEXXANDRO23** [comment]
I use the right button

**Comment by alexvornoffice** [comment]
I do too, when to wait for fix? I can fix ...
Why to brake something what works, add new featured not to remove old good features...

**Comment by zbot473** [comment]
I fixed it i think try reinstalling completely
