### ISSUE TITLE
 Aimbot

### ISSUE THREAD

**Issue by RuanTM** [zbot473/SurvivHacks#98]
zbot as before on the aimbot, could you move it to improve it? Why the configs that you indicated to me I already put and the aimbot is still not good

**Comment by zbot473** [comment]
What do you mean by not good?

**Comment by alexvornoffice** [comment]
AIM needs fix my bullets always skip the target when enemy is moving, so I need to move myself too to calibeate the bullets, I tried to fix but the code is very strange and complicated and biggest problem is that the variables are like: a, b, c, m, x, z what is what??? :(

**Comment by zbot473** [comment]
@ThanksMrSotarks which part are you having trouble with?
