### ISSUE TITLE
And how now to switch guns?

### ISSUE THREAD

**Issue by alexvornoffice** [zbot473/SurvivHacks#99]
**Describe the bug**
Can not switch guns right click;

**Expected behavior**
To change guns using right click;

**Comment by zbot473** [comment]
I guess ill make a toggle for that too

**Comment by alexvornoffice** [comment]
Maybe better to use space key for something, or for switching guns or for aim toggle...

**Comment by FallingBoi** [comment]
Maybe a menu where u can change the keys for the aim, toggle, etc.

**Comment by FallingBoi** [comment]
Nvm, plz fix it.

**Comment by RuanTM** [comment]
what I think is best for everyone is the aimbot in the right button and change the arming in space

**Comment by FallingBoi** [comment]
@RuanTM  Its a gud idea but how we can switch the guns?

**Comment by RuanTM** [comment]
in space fallboi like this in my trocar comment how to arm in space

**Comment by zbot473** [comment]
Im going to revert it.

**Comment by RuanTM** [comment]
revert not zbot puts to change weapon in shift and activate and deactivate the aimbot as long as it sits the right button

**Comment by zbot473** [comment]
???

**Comment by RuanTM** [comment]
zbot knows the shift where you put the aimbot? Then change it to the right mouse button.

**Comment by alexvornoffice** [comment]
why not use left mouse click? shooting and aim? maybe this will work

**Comment by ALEXXANDRO23** [comment]
It was better to change the weapon with the right button. :, /

**Comment by zbot473** [comment]
Fixed

**Comment by alexvornoffice** [comment]
not working :|

**Comment by zbot473** [comment]
Re install

**Comment by zbot473** [comment]
I can't test it out because i dont have a mouse
